{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spaceport.fullname" . }}-nginx
  labels:
    {{- include "spaceport.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |
    server {
        listen 80;
        root /usr/share/nginx/html;
        index index.html;

        location /otlp/ {
            proxy_pass {{ .Values.otlpEndpoint }}/;
            proxy_set_header Host $host;
        }

        location /chaos/ {
            proxy_pass http://{{ include "spaceport.fullname" . }}-pricing-service:8000/;
            proxy_set_header Host $host;
        }

        location /api/ {
            proxy_pass http://{{ include "spaceport.fullname" . }}-api:8080/api/;
            proxy_set_header Host $host;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
{{- end }}
