"""Semantic convention attribute constants.

DO NOT MODIFY: This code is autogenerated.
See templates/registry/python/attribute.py.j2.
"""

from __future__ import annotations


# --- Attribute keys ---


# Deprecated, use `client.address` instead.
HTTP_CLIENT_IP: str = "http.client_ip"

# State of the HTTP connection in the HTTP connection pool.
HTTP_CONNECTION_STATE: str = "http.connection.state"

# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR: str = "http.flavor"

# Deprecated, use one of `server.address`, `client.address` or
# `http.request.header.host` instead, depending on the usage.
HTTP_HOST: str = "http.host"

# Deprecated, use `http.request.method` instead.
HTTP_METHOD: str = "http.method"

# The size of the request payload body in bytes. This is the number of bytes
# transferred excluding headers and is often, but not always, present as the
# [Content-Length] header. For requests using transport encoding, this should be
# the compressed size.
#
# [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
HTTP_REQUEST_BODY_SIZE: str = "http.request.body.size"

# HTTP request headers, `<key>` being the normalized HTTP Header name
# (lowercase), the value being the header values.
HTTP_REQUEST_HEADER: str = "http.request.header"

# HTTP request method.
HTTP_REQUEST_METHOD: str = "http.request.method"

# Original HTTP method sent by the client in the request line.
HTTP_REQUEST_METHOD_ORIGINAL: str = "http.request.method_original"

# The ordinal number of request resending attempt (for any reason, including
# redirects).
HTTP_REQUEST_RESEND_COUNT: str = "http.request.resend_count"

# The total size of the request in bytes. This should be the total number of
# bytes sent over the wire, including the request line (HTTP/1.1), framing
# (HTTP/2 and HTTP/3), headers, and request body if any.
HTTP_REQUEST_SIZE: str = "http.request.size"

# Deprecated, use `http.request.header.content-length` instead.
HTTP_REQUEST_CONTENT_LENGTH: str = "http.request_content_length"

# Deprecated, use `http.request.body.size` instead.
HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED: str = "http.request_content_length_uncompressed"

# The size of the response payload body in bytes. This is the number of bytes
# transferred excluding headers and is often, but not always, present as the
# [Content-Length] header. For requests using transport encoding, this should be
# the compressed size.
#
# [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
HTTP_RESPONSE_BODY_SIZE: str = "http.response.body.size"

# HTTP response headers, `<key>` being the normalized HTTP Header name
# (lowercase), the value being the header values.
HTTP_RESPONSE_HEADER: str = "http.response.header"

# The total size of the response in bytes. This should be the total number of
# bytes sent over the wire, including the status line (HTTP/1.1), framing
# (HTTP/2 and HTTP/3), headers, and response body and trailers if any.
HTTP_RESPONSE_SIZE: str = "http.response.size"

# [HTTP response status code].
#
# [HTTP response status code]: https://tools.ietf.org/html/rfc7231#section-6
HTTP_RESPONSE_STATUS_CODE: str = "http.response.status_code"

# Deprecated, use `http.response.header.content-length` instead.
HTTP_RESPONSE_CONTENT_LENGTH: str = "http.response_content_length"

# Deprecated, use `http.response.body.size` instead.
HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED: str = "http.response_content_length_uncompressed"

# The matched route template for the request. This MUST be low-cardinality and
# include all static path segments, with dynamic path segments represented with
# placeholders.
HTTP_ROUTE: str = "http.route"

# Deprecated, use `url.scheme` instead.
HTTP_SCHEME: str = "http.scheme"

# Deprecated, use `server.address` instead.
HTTP_SERVER_NAME: str = "http.server_name"

# Deprecated, use `http.response.status_code` instead.
HTTP_STATUS_CODE: str = "http.status_code"

# Deprecated, use `url.path` and `url.query` instead.
HTTP_TARGET: str = "http.target"

# Deprecated, use `url.full` instead.
HTTP_URL: str = "http.url"

# Deprecated, use `user_agent.original` instead.
HTTP_USER_AGENT: str = "http.user_agent"

# Unique identifier for the booking.
SPACEPORT_BOOKING_ID: str = "spaceport.booking.id"

# Status of the booking.
SPACEPORT_BOOKING_STATUS: str = "spaceport.booking.status"

# The type of failure injected by the chaos module.
SPACEPORT_CHAOS_FAILURE_MODE: str = "spaceport.chaos.failure_mode"

# Artificial latency injected by the chaos module in milliseconds.
SPACEPORT_CHAOS_LATENCY_MS: str = "spaceport.chaos.latency_ms"

# Scheduled departure time in ISO 8601 format.
SPACEPORT_DEPARTURE_DEPARTURE_TIME: str = "spaceport.departure.departure_time"

# Destination of the departure (e.g. planet, station, or sector name).
SPACEPORT_DEPARTURE_DESTINATION: str = "spaceport.departure.destination"

# Unique identifier for the departure.
SPACEPORT_DEPARTURE_ID: str = "spaceport.departure.id"

# The base currency used for pricing. Always "UNC".
SPACEPORT_PRICING_BASE_CURRENCY: str = "spaceport.pricing.base_currency"

# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY: str = "spaceport.pricing.display_currency"

# Error message returned by the pricing service on failure.
SPACEPORT_PRICING_ERROR: str = "spaceport.pricing.error"

# Whether a promotional discount was applied to the booking.
SPACEPORT_PRICING_PROMO_APPLIED: str = "spaceport.pricing.promo_applied"

# Total price of the booking in Universal Nano Credits (UNC).
SPACEPORT_PRICING_TOTAL: str = "spaceport.pricing.total"

# Error message returned by the recommendations service on failure.
SPACEPORT_RECOMMENDATIONS_ERROR: str = "spaceport.recommendations.error"

# The seat class selected for the booking.
SPACEPORT_SEAT_CLASS: str = "spaceport.seat.class"

# Domain extracted from the `url.full`, such as "opentelemetry.io".
URL_DOMAIN: str = "url.domain"

# The file extension extracted from the `url.full`, excluding the leading dot.
URL_EXTENSION: str = "url.extension"

# The [URI fragment] component
#
# [URI fragment]: https://www.rfc-editor.org/rfc/rfc3986#section-3.5
URL_FRAGMENT: str = "url.fragment"

# Absolute URL describing a network resource according to [RFC3986]
#
# [RFC3986]: https://www.rfc-editor.org/rfc/rfc3986
URL_FULL: str = "url.full"

# Unmodified original URL as seen in the event source.
URL_ORIGINAL: str = "url.original"

# The [URI path] component
#
# [URI path]: https://www.rfc-editor.org/rfc/rfc3986#section-3.3
URL_PATH: str = "url.path"

# Port extracted from the `url.full`
URL_PORT: str = "url.port"

# The [URI query] component
#
# [URI query]: https://www.rfc-editor.org/rfc/rfc3986#section-3.4
URL_QUERY: str = "url.query"

# The highest registered url domain, stripped of the subdomain.
URL_REGISTERED_DOMAIN: str = "url.registered_domain"

# The [URI scheme] component identifying the used protocol.
#
# [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
URL_SCHEME: str = "url.scheme"

# The subdomain portion of a fully qualified domain name includes all of the
# names except the host name under the registered_domain. In a partially
# qualified domain, or if the qualification level of the full name cannot be
# determined, subdomain contains all of the names below the registered domain.
URL_SUBDOMAIN: str = "url.subdomain"

# The low-cardinality template of an [absolute path reference].
#
# [absolute path reference]: https://www.rfc-editor.org/rfc/rfc3986#section-4.2
URL_TEMPLATE: str = "url.template"

# The effective top level domain (eTLD), also known as the domain suffix, is the
# last part of the domain name. For example, the top level domain for
# example.com is `com`.
URL_TOP_LEVEL_DOMAIN: str = "url.top_level_domain"

# --- Enum values ---


# Enum values for http.connection.state.
# State of the HTTP connection in the HTTP connection pool.
HTTP_CONNECTION_STATE_ACTIVE: str = "active"
# State of the HTTP connection in the HTTP connection pool.
HTTP_CONNECTION_STATE_IDLE: str = "idle"

# Enum values for http.flavor.
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_HTTP_1_0: str = "1.0"
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_HTTP_1_1: str = "1.1"
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_HTTP_2_0: str = "2.0"
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_HTTP_3_0: str = "3.0"
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_SPDY: str = "SPDY"
# Deprecated, use `network.protocol.name` and `network.protocol.version`
# instead.
HTTP_FLAVOR_QUIC: str = "QUIC"

# Enum values for http.request.method.
# HTTP request method.
HTTP_REQUEST_METHOD_CONNECT: str = "CONNECT"
# HTTP request method.
HTTP_REQUEST_METHOD_DELETE: str = "DELETE"
# HTTP request method.
HTTP_REQUEST_METHOD_GET: str = "GET"
# HTTP request method.
HTTP_REQUEST_METHOD_HEAD: str = "HEAD"
# HTTP request method.
HTTP_REQUEST_METHOD_OPTIONS: str = "OPTIONS"
# HTTP request method.
HTTP_REQUEST_METHOD_PATCH: str = "PATCH"
# HTTP request method.
HTTP_REQUEST_METHOD_POST: str = "POST"
# HTTP request method.
HTTP_REQUEST_METHOD_PUT: str = "PUT"
# HTTP request method.
HTTP_REQUEST_METHOD_TRACE: str = "TRACE"
# HTTP request method.
HTTP_REQUEST_METHOD_QUERY: str = "QUERY"
# HTTP request method.
HTTP_REQUEST_METHOD_OTHER: str = "_OTHER"

# Enum values for spaceport.booking.status.
# Status of the booking.
SPACEPORT_BOOKING_STATUS_CONFIRMED: str = "confirmed"
# Status of the booking.
SPACEPORT_BOOKING_STATUS_FAILED: str = "failed"

# Enum values for spaceport.pricing.display_currency.
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_UNC: str = "UNC"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_REP: str = "REP"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_LAT: str = "LAT"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_QUA: str = "QUA"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_NIN: str = "NIN"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_BZD: str = "BZD"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_COIN: str = "COIN"
# The currency in which the price is displayed to the user.
SPACEPORT_PRICING_DISPLAY_CURRENCY_TKN: str = "TKN"

# Enum values for spaceport.seat.class.
# The seat class selected for the booking.
SPACEPORT_SEAT_CLASS_ECONOMY_CRYOSLEEP: str = "economy-cryosleep"
# The seat class selected for the booking.
SPACEPORT_SEAT_CLASS_BUSINESS_WARP: str = "business-warp"
# The seat class selected for the booking.
SPACEPORT_SEAT_CLASS_FIRST_CLASS_NEBULA: str = "first-class-nebula"