"""Semantic convention metric instruments.

DO NOT MODIFY: This code is autogenerated.
See templates/registry/python/metric.py.j2.
"""

from __future__ import annotations

from typing import Optional, Sequence

from opentelemetry.metrics import Meter, Counter, Histogram, UpDownCounter

from . import attribute


class HttpServerActive_requests:
    """Number of active HTTP server requests."""

    name = "http.server.active_requests"
    unit = "{request}"
    description = "Number of active HTTP server requests."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_up_down_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        http_request_method: str,
        url_scheme: str,
        server_address: Optional[str] = None,
        server_port: Optional[int] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.HTTP_REQUEST_METHOD: http_request_method,
            attribute.URL_SCHEME: url_scheme,
        }
        if server_address is not None:
            attrs[attribute.SERVER_ADDRESS] = server_address
        if server_port is not None:
            attrs[attribute.SERVER_PORT] = server_port
        self._inst.add(value, attributes=attrs)


class HttpServerRequestBodySize:
    """Size of HTTP server request bodies."""

    name = "http.server.request.body.size"
    unit = "By"
    description = "Size of HTTP server request bodies."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        http_request_method: str,
        url_scheme: str,
        error_type: Optional[str] = None,
        http_response_status_code: Optional[int] = None,
        http_route: Optional[str] = None,
        network_protocol_name: Optional[str] = None,
        network_protocol_version: Optional[str] = None,
        server_address: Optional[str] = None,
        server_port: Optional[int] = None,
        user_agent_synthetic_type: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.HTTP_REQUEST_METHOD: http_request_method,
            attribute.URL_SCHEME: url_scheme,
        }
        if error_type is not None:
            attrs[attribute.ERROR_TYPE] = error_type
        if http_response_status_code is not None:
            attrs[attribute.HTTP_RESPONSE_STATUS_CODE] = http_response_status_code
        if http_route is not None:
            attrs[attribute.HTTP_ROUTE] = http_route
        if network_protocol_name is not None:
            attrs[attribute.NETWORK_PROTOCOL_NAME] = network_protocol_name
        if network_protocol_version is not None:
            attrs[attribute.NETWORK_PROTOCOL_VERSION] = network_protocol_version
        if server_address is not None:
            attrs[attribute.SERVER_ADDRESS] = server_address
        if server_port is not None:
            attrs[attribute.SERVER_PORT] = server_port
        if user_agent_synthetic_type is not None:
            attrs[attribute.USER_AGENT_SYNTHETIC_TYPE] = user_agent_synthetic_type
        self._inst.record(value, attributes=attrs)


class HttpServerRequestDuration:
    """Duration of HTTP server requests."""

    name = "http.server.request.duration"
    unit = "s"
    description = "Duration of HTTP server requests."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        http_request_method: str,
        url_scheme: str,
        error_type: Optional[str] = None,
        http_response_status_code: Optional[int] = None,
        http_route: Optional[str] = None,
        network_protocol_name: Optional[str] = None,
        network_protocol_version: Optional[str] = None,
        server_address: Optional[str] = None,
        server_port: Optional[int] = None,
        user_agent_synthetic_type: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.HTTP_REQUEST_METHOD: http_request_method,
            attribute.URL_SCHEME: url_scheme,
        }
        if error_type is not None:
            attrs[attribute.ERROR_TYPE] = error_type
        if http_response_status_code is not None:
            attrs[attribute.HTTP_RESPONSE_STATUS_CODE] = http_response_status_code
        if http_route is not None:
            attrs[attribute.HTTP_ROUTE] = http_route
        if network_protocol_name is not None:
            attrs[attribute.NETWORK_PROTOCOL_NAME] = network_protocol_name
        if network_protocol_version is not None:
            attrs[attribute.NETWORK_PROTOCOL_VERSION] = network_protocol_version
        if server_address is not None:
            attrs[attribute.SERVER_ADDRESS] = server_address
        if server_port is not None:
            attrs[attribute.SERVER_PORT] = server_port
        if user_agent_synthetic_type is not None:
            attrs[attribute.USER_AGENT_SYNTHETIC_TYPE] = user_agent_synthetic_type
        self._inst.record(value, attributes=attrs)


class HttpServerResponseBodySize:
    """Size of HTTP server response bodies."""

    name = "http.server.response.body.size"
    unit = "By"
    description = "Size of HTTP server response bodies."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        http_request_method: str,
        url_scheme: str,
        error_type: Optional[str] = None,
        http_response_status_code: Optional[int] = None,
        http_route: Optional[str] = None,
        network_protocol_name: Optional[str] = None,
        network_protocol_version: Optional[str] = None,
        server_address: Optional[str] = None,
        server_port: Optional[int] = None,
        user_agent_synthetic_type: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.HTTP_REQUEST_METHOD: http_request_method,
            attribute.URL_SCHEME: url_scheme,
        }
        if error_type is not None:
            attrs[attribute.ERROR_TYPE] = error_type
        if http_response_status_code is not None:
            attrs[attribute.HTTP_RESPONSE_STATUS_CODE] = http_response_status_code
        if http_route is not None:
            attrs[attribute.HTTP_ROUTE] = http_route
        if network_protocol_name is not None:
            attrs[attribute.NETWORK_PROTOCOL_NAME] = network_protocol_name
        if network_protocol_version is not None:
            attrs[attribute.NETWORK_PROTOCOL_VERSION] = network_protocol_version
        if server_address is not None:
            attrs[attribute.SERVER_ADDRESS] = server_address
        if server_port is not None:
            attrs[attribute.SERVER_PORT] = server_port
        if user_agent_synthetic_type is not None:
            attrs[attribute.USER_AGENT_SYNTHETIC_TYPE] = user_agent_synthetic_type
        self._inst.record(value, attributes=attrs)


class SpaceportBookingActive:
    """Number of confirmed bookings currently in the system."""

    name = "spaceport.booking.active"
    unit = "{booking}"
    description = "Number of confirmed bookings currently in the system."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_up_down_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
        }
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportBookingCount:
    """Number of booking attempts processed by the API."""

    name = "spaceport.booking.count"
    unit = "{booking}"
    description = "Number of booking attempts processed by the API."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_booking_status: str,
        spaceport_departure_destination: Optional[str] = None,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_BOOKING_STATUS: spaceport_booking_status,
        }
        if spaceport_departure_destination is not None:
            attrs[attribute.SPACEPORT_DEPARTURE_DESTINATION] = spaceport_departure_destination
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportDepartureActive:
    """Number of departures currently available for booking."""

    name = "spaceport.departure.active"
    unit = "{departure}"
    description = "Number of departures currently available for booking."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_up_down_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_departure_destination: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
        }
        if spaceport_departure_destination is not None:
            attrs[attribute.SPACEPORT_DEPARTURE_DESTINATION] = spaceport_departure_destination
        self._inst.add(value, attributes=attrs)


class SpaceportFrontendBookings:
    """Booking attempts made from the frontend."""

    name = "spaceport.frontend.bookings"
    unit = "{booking}"
    description = "Booking attempts made from the frontend."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        outcome: str,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.OUTCOME: outcome,
        }
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportFrontendExhibit_dwell_time:
    """Time an exhibit remained visible in the viewport."""

    name = "spaceport.frontend.exhibit_dwell_time"
    unit = "s"
    description = "Time an exhibit remained visible in the viewport."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        spaceport_exhibit_id: str,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_EXHIBIT_ID: spaceport_exhibit_id,
        }
        self._inst.record(value, attributes=attrs)


class SpaceportFrontendExhibit_views:
    """Number of times an exhibit section scrolled into the viewport."""

    name = "spaceport.frontend.exhibit_views"
    unit = "{view}"
    description = "Number of times an exhibit section scrolled into the viewport."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_exhibit_id: str,
        spaceport_exhibit_title: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_EXHIBIT_ID: spaceport_exhibit_id,
        }
        if spaceport_exhibit_title is not None:
            attrs[attribute.SPACEPORT_EXHIBIT_TITLE] = spaceport_exhibit_title
        self._inst.add(value, attributes=attrs)


class SpaceportFrontendPage_views:
    """Page views counted by page name."""

    name = "spaceport.frontend.page_views"
    unit = "{view}"
    description = "Page views counted by page name."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        page_name: str,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.PAGE_NAME: page_name,
        }
        self._inst.add(value, attributes=attrs)


class SpaceportPricingFailuresCount:
    """Number of pricing service call failures from the API."""

    name = "spaceport.pricing.failures.count"
    unit = "{failure}"
    description = "Number of pricing service call failures from the API."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
        }
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportPricingRequestDuration:
    """Duration of price calculation requests from the API to the pricing service."""

    name = "spaceport.pricing.request.duration"
    unit = "ms"
    description = "Duration of price calculation requests from the API to the pricing service."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        spaceport_seat_class: str,
        spaceport_pricing_display_currency: Optional[str] = None,
        spaceport_pricing_promo_applied: Optional[bool] = None,
        spaceport_chaos_failure_mode: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_SEAT_CLASS: spaceport_seat_class,
        }
        if spaceport_pricing_display_currency is not None:
            attrs[attribute.SPACEPORT_PRICING_DISPLAY_CURRENCY] = spaceport_pricing_display_currency
        if spaceport_pricing_promo_applied is not None:
            attrs[attribute.SPACEPORT_PRICING_PROMO_APPLIED] = spaceport_pricing_promo_applied
        if spaceport_chaos_failure_mode is not None:
            attrs[attribute.SPACEPORT_CHAOS_FAILURE_MODE] = spaceport_chaos_failure_mode
        self._inst.record(value, attributes=attrs)