"""Semantic convention metric instruments.

DO NOT MODIFY: This code is autogenerated.
See templates/registry/python/metric.py.j2.
"""

from __future__ import annotations

from typing import Optional, Sequence

from opentelemetry.metrics import Meter, Counter, Histogram, UpDownCounter

from . import attribute


class SpaceportBookingActive:
    """Number of confirmed bookings currently in the system."""

    name = "spaceport.booking.active"
    unit = "{booking}"
    description = "Number of confirmed bookings currently in the system."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_up_down_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
        }
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportBookingCount:
    """Number of booking attempts processed by the API."""

    name = "spaceport.booking.count"
    unit = "{booking}"
    description = "Number of booking attempts processed by the API."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_booking_status: str,
        spaceport_departure_destination: Optional[str] = None,
        spaceport_seat_class: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_BOOKING_STATUS: spaceport_booking_status,
        }
        if spaceport_departure_destination is not None:
            attrs[attribute.SPACEPORT_DEPARTURE_DESTINATION] = spaceport_departure_destination
        if spaceport_seat_class is not None:
            attrs[attribute.SPACEPORT_SEAT_CLASS] = spaceport_seat_class
        self._inst.add(value, attributes=attrs)


class SpaceportDepartureActive:
    """Number of departures currently available for booking."""

    name = "spaceport.departure.active"
    unit = "{departure}"
    description = "Number of departures currently available for booking."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_up_down_counter(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def add(
        self,
        value: float,
        spaceport_departure_destination: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
        }
        if spaceport_departure_destination is not None:
            attrs[attribute.SPACEPORT_DEPARTURE_DESTINATION] = spaceport_departure_destination
        self._inst.add(value, attributes=attrs)


class SpaceportPricingRequestDuration:
    """Duration of price calculation requests from the API to the pricing service."""

    name = "spaceport.pricing.request.duration"
    unit = "ms"
    description = "Duration of price calculation requests from the API to the pricing service."

    def __init__(self, meter: Meter) -> None:
        self._inst = meter.create_histogram(
            name=self.name,
            description=self.description,
            unit=self.unit,
        )

    def record(
        self,
        value: float,
        spaceport_seat_class: str,
        spaceport_pricing_display_currency: Optional[str] = None,
        spaceport_pricing_promo_applied: Optional[bool] = None,
        spaceport_chaos_failure_mode: Optional[str] = None,
    ) -> None:
        attrs: dict[str, str | int | float | bool | Sequence] = {
            attribute.SPACEPORT_SEAT_CLASS: spaceport_seat_class,
        }
        if spaceport_pricing_display_currency is not None:
            attrs[attribute.SPACEPORT_PRICING_DISPLAY_CURRENCY] = spaceport_pricing_display_currency
        if spaceport_pricing_promo_applied is not None:
            attrs[attribute.SPACEPORT_PRICING_PROMO_APPLIED] = spaceport_pricing_promo_applied
        if spaceport_chaos_failure_mode is not None:
            attrs[attribute.SPACEPORT_CHAOS_FAILURE_MODE] = spaceport_chaos_failure_mode
        self._inst.record(value, attributes=attrs)