package semconv

import "go.opentelemetry.io/otel/attribute"

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/attribute.go.j2.

// --- Attribute keys ---


// A message providing more detail about an error in human-readable form.
const AttrErrorMessageKey = attribute.Key("error.message")

// Describes a class of error the operation ended with.
const AttrErrorTypeKey = attribute.Key("error.type")

// Deprecated, use `client.address` instead.
const AttrHttpClientIpKey = attribute.Key("http.client_ip")

// State of the HTTP connection in the HTTP connection pool.
const AttrHttpConnectionStateKey = attribute.Key("http.connection.state")

// Deprecated, use `network.protocol.name` and `network.protocol.version`
// instead.
const AttrHttpFlavorKey = attribute.Key("http.flavor")

// Deprecated, use one of `server.address`, `client.address` or
// `http.request.header.host` instead, depending on the usage.
const AttrHttpHostKey = attribute.Key("http.host")

// Deprecated, use `http.request.method` instead.
const AttrHttpMethodKey = attribute.Key("http.method")

// The size of the request payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
const AttrHttpRequestBodySizeKey = attribute.Key("http.request.body.size")

// HTTP request headers, `<key>` being the normalized HTTP Header name
// (lowercase), the value being the header values.
const AttrHttpRequestHeaderKey = attribute.Key("http.request.header")

// HTTP request method.
const AttrHttpRequestMethodKey = attribute.Key("http.request.method")

// Original HTTP method sent by the client in the request line.
const AttrHttpRequestMethodOriginalKey = attribute.Key("http.request.method_original")

// The ordinal number of request resending attempt (for any reason, including
// redirects).
const AttrHttpRequestResendCountKey = attribute.Key("http.request.resend_count")

// The total size of the request in bytes. This should be the total number of
// bytes sent over the wire, including the request line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and request body if any.
const AttrHttpRequestSizeKey = attribute.Key("http.request.size")

// Deprecated, use `http.request.header.content-length` instead.
const AttrHttpRequestContentLengthKey = attribute.Key("http.request_content_length")

// Deprecated, use `http.request.body.size` instead.
const AttrHttpRequestContentLengthUncompressedKey = attribute.Key("http.request_content_length_uncompressed")

// The size of the response payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
const AttrHttpResponseBodySizeKey = attribute.Key("http.response.body.size")

// HTTP response headers, `<key>` being the normalized HTTP Header name
// (lowercase), the value being the header values.
const AttrHttpResponseHeaderKey = attribute.Key("http.response.header")

// The total size of the response in bytes. This should be the total number of
// bytes sent over the wire, including the status line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and response body and trailers if any.
const AttrHttpResponseSizeKey = attribute.Key("http.response.size")

// [HTTP response status code].
//
// [HTTP response status code]: https://tools.ietf.org/html/rfc7231#section-6
const AttrHttpResponseStatusCodeKey = attribute.Key("http.response.status_code")

// Deprecated, use `http.response.header.content-length` instead.
const AttrHttpResponseContentLengthKey = attribute.Key("http.response_content_length")

// Deprecated, use `http.response.body.size` instead.
const AttrHttpResponseContentLengthUncompressedKey = attribute.Key("http.response_content_length_uncompressed")

// The matched route template for the request. This MUST be low-cardinality and
// include all static path segments, with dynamic path segments represented with
// placeholders.
const AttrHttpRouteKey = attribute.Key("http.route")

// Deprecated, use `url.scheme` instead.
const AttrHttpSchemeKey = attribute.Key("http.scheme")

// Deprecated, use `server.address` instead.
const AttrHttpServerNameKey = attribute.Key("http.server_name")

// Deprecated, use `http.response.status_code` instead.
const AttrHttpStatusCodeKey = attribute.Key("http.status_code")

// Deprecated, use `url.path` and `url.query` instead.
const AttrHttpTargetKey = attribute.Key("http.target")

// Deprecated, use `url.full` instead.
const AttrHttpUrlKey = attribute.Key("http.url")

// Deprecated, use `user_agent.original` instead.
const AttrHttpUserAgentKey = attribute.Key("http.user_agent")

// The ISO 3166-1 alpha-2 2-character country code associated with the mobile
// carrier network.
const AttrNetworkCarrierIccKey = attribute.Key("network.carrier.icc")

// The mobile carrier country code.
const AttrNetworkCarrierMccKey = attribute.Key("network.carrier.mcc")

// The mobile carrier network code.
const AttrNetworkCarrierMncKey = attribute.Key("network.carrier.mnc")

// The name of the mobile carrier.
const AttrNetworkCarrierNameKey = attribute.Key("network.carrier.name")

// The state of network connection
const AttrNetworkConnectionStateKey = attribute.Key("network.connection.state")

// This describes more details regarding the connection.type. It may be the type
// of cell technology connection, but it could be used for describing details
// about a wifi connection.
const AttrNetworkConnectionSubtypeKey = attribute.Key("network.connection.subtype")

// The internet connection type.
const AttrNetworkConnectionTypeKey = attribute.Key("network.connection.type")

// The network interface name.
const AttrNetworkInterfaceNameKey = attribute.Key("network.interface.name")

// The network IO operation direction.
const AttrNetworkIoDirectionKey = attribute.Key("network.io.direction")

// Local address of the network connection - IP address or Unix domain socket
// name.
const AttrNetworkLocalAddressKey = attribute.Key("network.local.address")

// Local port number of the network connection.
const AttrNetworkLocalPortKey = attribute.Key("network.local.port")

// Peer address of the network connection - IP address or Unix domain socket
// name.
const AttrNetworkPeerAddressKey = attribute.Key("network.peer.address")

// Peer port number of the network connection.
const AttrNetworkPeerPortKey = attribute.Key("network.peer.port")

// [OSI application layer] or non-OSI equivalent.
//
// [OSI application layer]: https://wikipedia.org/wiki/Application_layer
const AttrNetworkProtocolNameKey = attribute.Key("network.protocol.name")

// The actual version of the protocol used for network communication.
const AttrNetworkProtocolVersionKey = attribute.Key("network.protocol.version")

// [OSI transport layer] or [inter-process communication method].
//
// [OSI transport layer]: https://wikipedia.org/wiki/Transport_layer
// [inter-process communication method]: https://wikipedia.org/wiki/Inter-process_communication
const AttrNetworkTransportKey = attribute.Key("network.transport")

// [OSI network layer] or non-OSI equivalent.
//
// [OSI network layer]: https://wikipedia.org/wiki/Network_layer
const AttrNetworkTypeKey = attribute.Key("network.type")

// Server domain name if available without reverse DNS lookup; otherwise, IP
// address or Unix domain socket name.
const AttrServerAddressKey = attribute.Key("server.address")

// Server port number.
const AttrServerPortKey = attribute.Key("server.port")

// Unique identifier for the booking.
const AttrSpaceportBookingIdKey = attribute.Key("spaceport.booking.id")

// Status of the booking.
const AttrSpaceportBookingStatusKey = attribute.Key("spaceport.booking.status")

// The type of failure injected by the chaos module.
const AttrSpaceportChaosFailureModeKey = attribute.Key("spaceport.chaos.failure_mode")

// Artificial latency injected by the chaos module in milliseconds.
const AttrSpaceportChaosLatencyMsKey = attribute.Key("spaceport.chaos.latency_ms")

// Scheduled departure time in ISO 8601 format.
const AttrSpaceportDepartureDepartureTimeKey = attribute.Key("spaceport.departure.departure_time")

// Destination of the departure (e.g. planet, station, or sector name).
const AttrSpaceportDepartureDestinationKey = attribute.Key("spaceport.departure.destination")

// Unique identifier for the departure.
const AttrSpaceportDepartureIdKey = attribute.Key("spaceport.departure.id")

// URL-safe slug identifying the exhibit section.
const AttrSpaceportExhibitIdKey = attribute.Key("spaceport.exhibit.id")

// Human-readable title of the exhibit.
const AttrSpaceportExhibitTitleKey = attribute.Key("spaceport.exhibit.title")

// The base currency used for pricing. Always "UNC".
const AttrSpaceportPricingBaseCurrencyKey = attribute.Key("spaceport.pricing.base_currency")

// The currency in which the price is displayed to the user.
const AttrSpaceportPricingDisplayCurrencyKey = attribute.Key("spaceport.pricing.display_currency")

// Error message returned by the pricing service on failure.
const AttrSpaceportPricingErrorKey = attribute.Key("spaceport.pricing.error")

// Whether a promotional discount was applied to the booking.
const AttrSpaceportPricingPromoAppliedKey = attribute.Key("spaceport.pricing.promo_applied")

// Total price of the booking in Universal Nano Credits (UNC).
const AttrSpaceportPricingTotalKey = attribute.Key("spaceport.pricing.total")

// Error message returned by the recommendations service on failure.
const AttrSpaceportRecommendationsErrorKey = attribute.Key("spaceport.recommendations.error")

// The seat class selected for the booking.
const AttrSpaceportSeatClassKey = attribute.Key("spaceport.seat.class")

// Domain extracted from the `url.full`, such as "opentelemetry.io".
const AttrUrlDomainKey = attribute.Key("url.domain")

// The file extension extracted from the `url.full`, excluding the leading dot.
const AttrUrlExtensionKey = attribute.Key("url.extension")

// The [URI fragment] component
//
// [URI fragment]: https://www.rfc-editor.org/rfc/rfc3986#section-3.5
const AttrUrlFragmentKey = attribute.Key("url.fragment")

// Absolute URL describing a network resource according to [RFC3986]
//
// [RFC3986]: https://www.rfc-editor.org/rfc/rfc3986
const AttrUrlFullKey = attribute.Key("url.full")

// Unmodified original URL as seen in the event source.
const AttrUrlOriginalKey = attribute.Key("url.original")

// The [URI path] component
//
// [URI path]: https://www.rfc-editor.org/rfc/rfc3986#section-3.3
const AttrUrlPathKey = attribute.Key("url.path")

// Port extracted from the `url.full`
const AttrUrlPortKey = attribute.Key("url.port")

// The [URI query] component
//
// [URI query]: https://www.rfc-editor.org/rfc/rfc3986#section-3.4
const AttrUrlQueryKey = attribute.Key("url.query")

// The highest registered url domain, stripped of the subdomain.
const AttrUrlRegisteredDomainKey = attribute.Key("url.registered_domain")

// The [URI scheme] component identifying the used protocol.
//
// [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
const AttrUrlSchemeKey = attribute.Key("url.scheme")

// The subdomain portion of a fully qualified domain name includes all of the
// names except the host name under the registered_domain. In a partially
// qualified domain, or if the qualification level of the full name cannot be
// determined, subdomain contains all of the names below the registered domain.
const AttrUrlSubdomainKey = attribute.Key("url.subdomain")

// The low-cardinality template of an [absolute path reference].
//
// [absolute path reference]: https://www.rfc-editor.org/rfc/rfc3986#section-4.2
const AttrUrlTemplateKey = attribute.Key("url.template")

// The effective top level domain (eTLD), also known as the domain suffix, is the
// last part of the domain name. For example, the top level domain for
// example.com is `com`.
const AttrUrlTopLevelDomainKey = attribute.Key("url.top_level_domain")

// Total number of exhibits available in the presentation.
const AttrSpaceportExhibitCountKey = attribute.Key("spaceport.exhibit.count")

// Display order number of the exhibit (1-based).
const AttrSpaceportExhibitNumberKey = attribute.Key("spaceport.exhibit.number")

// --- Attribute value helpers ---


// A message providing more detail about an error in human-readable form.
func AttrErrorMessage(val string) attribute.KeyValue {
	return AttrErrorMessageKey.String(val)
}

// Describes a class of error the operation ended with.
func AttrErrorType(val string) attribute.KeyValue {
	return AttrErrorTypeKey.String(val)
}

// Deprecated, use `client.address` instead.
func AttrHttpClientIp(val string) attribute.KeyValue {
	return AttrHttpClientIpKey.String(val)
}

// State of the HTTP connection in the HTTP connection pool.
func AttrHttpConnectionState(val string) attribute.KeyValue {
	return AttrHttpConnectionStateKey.String(val)
}

// Deprecated, use `network.protocol.name` and `network.protocol.version`
// instead.
func AttrHttpFlavor(val string) attribute.KeyValue {
	return AttrHttpFlavorKey.String(val)
}

// Deprecated, use one of `server.address`, `client.address` or
// `http.request.header.host` instead, depending on the usage.
func AttrHttpHost(val string) attribute.KeyValue {
	return AttrHttpHostKey.String(val)
}

// Deprecated, use `http.request.method` instead.
func AttrHttpMethod(val string) attribute.KeyValue {
	return AttrHttpMethodKey.String(val)
}

// The size of the request payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
func AttrHttpRequestBodySize(val int) attribute.KeyValue {
	return AttrHttpRequestBodySizeKey.Int(val)
}

// HTTP request method.
func AttrHttpRequestMethod(val string) attribute.KeyValue {
	return AttrHttpRequestMethodKey.String(val)
}

// Original HTTP method sent by the client in the request line.
func AttrHttpRequestMethodOriginal(val string) attribute.KeyValue {
	return AttrHttpRequestMethodOriginalKey.String(val)
}

// The ordinal number of request resending attempt (for any reason, including
// redirects).
func AttrHttpRequestResendCount(val int) attribute.KeyValue {
	return AttrHttpRequestResendCountKey.Int(val)
}

// The total size of the request in bytes. This should be the total number of
// bytes sent over the wire, including the request line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and request body if any.
func AttrHttpRequestSize(val int) attribute.KeyValue {
	return AttrHttpRequestSizeKey.Int(val)
}

// Deprecated, use `http.request.header.content-length` instead.
func AttrHttpRequestContentLength(val int) attribute.KeyValue {
	return AttrHttpRequestContentLengthKey.Int(val)
}

// Deprecated, use `http.request.body.size` instead.
func AttrHttpRequestContentLengthUncompressed(val int) attribute.KeyValue {
	return AttrHttpRequestContentLengthUncompressedKey.Int(val)
}

// The size of the response payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
func AttrHttpResponseBodySize(val int) attribute.KeyValue {
	return AttrHttpResponseBodySizeKey.Int(val)
}

// The total size of the response in bytes. This should be the total number of
// bytes sent over the wire, including the status line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and response body and trailers if any.
func AttrHttpResponseSize(val int) attribute.KeyValue {
	return AttrHttpResponseSizeKey.Int(val)
}

// [HTTP response status code].
//
// [HTTP response status code]: https://tools.ietf.org/html/rfc7231#section-6
func AttrHttpResponseStatusCode(val int) attribute.KeyValue {
	return AttrHttpResponseStatusCodeKey.Int(val)
}

// Deprecated, use `http.response.header.content-length` instead.
func AttrHttpResponseContentLength(val int) attribute.KeyValue {
	return AttrHttpResponseContentLengthKey.Int(val)
}

// Deprecated, use `http.response.body.size` instead.
func AttrHttpResponseContentLengthUncompressed(val int) attribute.KeyValue {
	return AttrHttpResponseContentLengthUncompressedKey.Int(val)
}

// The matched route template for the request. This MUST be low-cardinality and
// include all static path segments, with dynamic path segments represented with
// placeholders.
func AttrHttpRoute(val string) attribute.KeyValue {
	return AttrHttpRouteKey.String(val)
}

// Deprecated, use `url.scheme` instead.
func AttrHttpScheme(val string) attribute.KeyValue {
	return AttrHttpSchemeKey.String(val)
}

// Deprecated, use `server.address` instead.
func AttrHttpServerName(val string) attribute.KeyValue {
	return AttrHttpServerNameKey.String(val)
}

// Deprecated, use `http.response.status_code` instead.
func AttrHttpStatusCode(val int) attribute.KeyValue {
	return AttrHttpStatusCodeKey.Int(val)
}

// Deprecated, use `url.path` and `url.query` instead.
func AttrHttpTarget(val string) attribute.KeyValue {
	return AttrHttpTargetKey.String(val)
}

// Deprecated, use `url.full` instead.
func AttrHttpUrl(val string) attribute.KeyValue {
	return AttrHttpUrlKey.String(val)
}

// Deprecated, use `user_agent.original` instead.
func AttrHttpUserAgent(val string) attribute.KeyValue {
	return AttrHttpUserAgentKey.String(val)
}

// The ISO 3166-1 alpha-2 2-character country code associated with the mobile
// carrier network.
func AttrNetworkCarrierIcc(val string) attribute.KeyValue {
	return AttrNetworkCarrierIccKey.String(val)
}

// The mobile carrier country code.
func AttrNetworkCarrierMcc(val string) attribute.KeyValue {
	return AttrNetworkCarrierMccKey.String(val)
}

// The mobile carrier network code.
func AttrNetworkCarrierMnc(val string) attribute.KeyValue {
	return AttrNetworkCarrierMncKey.String(val)
}

// The name of the mobile carrier.
func AttrNetworkCarrierName(val string) attribute.KeyValue {
	return AttrNetworkCarrierNameKey.String(val)
}

// The state of network connection
func AttrNetworkConnectionState(val string) attribute.KeyValue {
	return AttrNetworkConnectionStateKey.String(val)
}

// This describes more details regarding the connection.type. It may be the type
// of cell technology connection, but it could be used for describing details
// about a wifi connection.
func AttrNetworkConnectionSubtype(val string) attribute.KeyValue {
	return AttrNetworkConnectionSubtypeKey.String(val)
}

// The internet connection type.
func AttrNetworkConnectionType(val string) attribute.KeyValue {
	return AttrNetworkConnectionTypeKey.String(val)
}

// The network interface name.
func AttrNetworkInterfaceName(val string) attribute.KeyValue {
	return AttrNetworkInterfaceNameKey.String(val)
}

// The network IO operation direction.
func AttrNetworkIoDirection(val string) attribute.KeyValue {
	return AttrNetworkIoDirectionKey.String(val)
}

// Local address of the network connection - IP address or Unix domain socket
// name.
func AttrNetworkLocalAddress(val string) attribute.KeyValue {
	return AttrNetworkLocalAddressKey.String(val)
}

// Local port number of the network connection.
func AttrNetworkLocalPort(val int) attribute.KeyValue {
	return AttrNetworkLocalPortKey.Int(val)
}

// Peer address of the network connection - IP address or Unix domain socket
// name.
func AttrNetworkPeerAddress(val string) attribute.KeyValue {
	return AttrNetworkPeerAddressKey.String(val)
}

// Peer port number of the network connection.
func AttrNetworkPeerPort(val int) attribute.KeyValue {
	return AttrNetworkPeerPortKey.Int(val)
}

// [OSI application layer] or non-OSI equivalent.
//
// [OSI application layer]: https://wikipedia.org/wiki/Application_layer
func AttrNetworkProtocolName(val string) attribute.KeyValue {
	return AttrNetworkProtocolNameKey.String(val)
}

// The actual version of the protocol used for network communication.
func AttrNetworkProtocolVersion(val string) attribute.KeyValue {
	return AttrNetworkProtocolVersionKey.String(val)
}

// [OSI transport layer] or [inter-process communication method].
//
// [OSI transport layer]: https://wikipedia.org/wiki/Transport_layer
// [inter-process communication method]: https://wikipedia.org/wiki/Inter-process_communication
func AttrNetworkTransport(val string) attribute.KeyValue {
	return AttrNetworkTransportKey.String(val)
}

// [OSI network layer] or non-OSI equivalent.
//
// [OSI network layer]: https://wikipedia.org/wiki/Network_layer
func AttrNetworkType(val string) attribute.KeyValue {
	return AttrNetworkTypeKey.String(val)
}

// Server domain name if available without reverse DNS lookup; otherwise, IP
// address or Unix domain socket name.
func AttrServerAddress(val string) attribute.KeyValue {
	return AttrServerAddressKey.String(val)
}

// Server port number.
func AttrServerPort(val int) attribute.KeyValue {
	return AttrServerPortKey.Int(val)
}

// Unique identifier for the booking.
func AttrSpaceportBookingId(val string) attribute.KeyValue {
	return AttrSpaceportBookingIdKey.String(val)
}

// Status of the booking.
func AttrSpaceportBookingStatus(val string) attribute.KeyValue {
	return AttrSpaceportBookingStatusKey.String(val)
}

// The type of failure injected by the chaos module.
func AttrSpaceportChaosFailureMode(val string) attribute.KeyValue {
	return AttrSpaceportChaosFailureModeKey.String(val)
}

// Artificial latency injected by the chaos module in milliseconds.
func AttrSpaceportChaosLatencyMs(val int) attribute.KeyValue {
	return AttrSpaceportChaosLatencyMsKey.Int(val)
}

// Scheduled departure time in ISO 8601 format.
func AttrSpaceportDepartureDepartureTime(val string) attribute.KeyValue {
	return AttrSpaceportDepartureDepartureTimeKey.String(val)
}

// Destination of the departure (e.g. planet, station, or sector name).
func AttrSpaceportDepartureDestination(val string) attribute.KeyValue {
	return AttrSpaceportDepartureDestinationKey.String(val)
}

// Unique identifier for the departure.
func AttrSpaceportDepartureId(val string) attribute.KeyValue {
	return AttrSpaceportDepartureIdKey.String(val)
}

// URL-safe slug identifying the exhibit section.
func AttrSpaceportExhibitId(val string) attribute.KeyValue {
	return AttrSpaceportExhibitIdKey.String(val)
}

// Human-readable title of the exhibit.
func AttrSpaceportExhibitTitle(val string) attribute.KeyValue {
	return AttrSpaceportExhibitTitleKey.String(val)
}

// The base currency used for pricing. Always "UNC".
func AttrSpaceportPricingBaseCurrency(val string) attribute.KeyValue {
	return AttrSpaceportPricingBaseCurrencyKey.String(val)
}

// The currency in which the price is displayed to the user.
func AttrSpaceportPricingDisplayCurrency(val string) attribute.KeyValue {
	return AttrSpaceportPricingDisplayCurrencyKey.String(val)
}

// Error message returned by the pricing service on failure.
func AttrSpaceportPricingError(val string) attribute.KeyValue {
	return AttrSpaceportPricingErrorKey.String(val)
}

// Whether a promotional discount was applied to the booking.
func AttrSpaceportPricingPromoApplied(val bool) attribute.KeyValue {
	return AttrSpaceportPricingPromoAppliedKey.Bool(val)
}

// Total price of the booking in Universal Nano Credits (UNC).
func AttrSpaceportPricingTotal(val float64) attribute.KeyValue {
	return AttrSpaceportPricingTotalKey.Float64(val)
}

// Error message returned by the recommendations service on failure.
func AttrSpaceportRecommendationsError(val string) attribute.KeyValue {
	return AttrSpaceportRecommendationsErrorKey.String(val)
}

// The seat class selected for the booking.
func AttrSpaceportSeatClass(val string) attribute.KeyValue {
	return AttrSpaceportSeatClassKey.String(val)
}

// Domain extracted from the `url.full`, such as "opentelemetry.io".
func AttrUrlDomain(val string) attribute.KeyValue {
	return AttrUrlDomainKey.String(val)
}

// The file extension extracted from the `url.full`, excluding the leading dot.
func AttrUrlExtension(val string) attribute.KeyValue {
	return AttrUrlExtensionKey.String(val)
}

// The [URI fragment] component
//
// [URI fragment]: https://www.rfc-editor.org/rfc/rfc3986#section-3.5
func AttrUrlFragment(val string) attribute.KeyValue {
	return AttrUrlFragmentKey.String(val)
}

// Absolute URL describing a network resource according to [RFC3986]
//
// [RFC3986]: https://www.rfc-editor.org/rfc/rfc3986
func AttrUrlFull(val string) attribute.KeyValue {
	return AttrUrlFullKey.String(val)
}

// Unmodified original URL as seen in the event source.
func AttrUrlOriginal(val string) attribute.KeyValue {
	return AttrUrlOriginalKey.String(val)
}

// The [URI path] component
//
// [URI path]: https://www.rfc-editor.org/rfc/rfc3986#section-3.3
func AttrUrlPath(val string) attribute.KeyValue {
	return AttrUrlPathKey.String(val)
}

// Port extracted from the `url.full`
func AttrUrlPort(val int) attribute.KeyValue {
	return AttrUrlPortKey.Int(val)
}

// The [URI query] component
//
// [URI query]: https://www.rfc-editor.org/rfc/rfc3986#section-3.4
func AttrUrlQuery(val string) attribute.KeyValue {
	return AttrUrlQueryKey.String(val)
}

// The highest registered url domain, stripped of the subdomain.
func AttrUrlRegisteredDomain(val string) attribute.KeyValue {
	return AttrUrlRegisteredDomainKey.String(val)
}

// The [URI scheme] component identifying the used protocol.
//
// [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
func AttrUrlScheme(val string) attribute.KeyValue {
	return AttrUrlSchemeKey.String(val)
}

// The subdomain portion of a fully qualified domain name includes all of the
// names except the host name under the registered_domain. In a partially
// qualified domain, or if the qualification level of the full name cannot be
// determined, subdomain contains all of the names below the registered domain.
func AttrUrlSubdomain(val string) attribute.KeyValue {
	return AttrUrlSubdomainKey.String(val)
}

// The low-cardinality template of an [absolute path reference].
//
// [absolute path reference]: https://www.rfc-editor.org/rfc/rfc3986#section-4.2
func AttrUrlTemplate(val string) attribute.KeyValue {
	return AttrUrlTemplateKey.String(val)
}

// The effective top level domain (eTLD), also known as the domain suffix, is the
// last part of the domain name. For example, the top level domain for
// example.com is `com`.
func AttrUrlTopLevelDomain(val string) attribute.KeyValue {
	return AttrUrlTopLevelDomainKey.String(val)
}

// Total number of exhibits available in the presentation.
func AttrSpaceportExhibitCount(val int) attribute.KeyValue {
	return AttrSpaceportExhibitCountKey.Int(val)
}

// Display order number of the exhibit (1-based).
func AttrSpaceportExhibitNumber(val int) attribute.KeyValue {
	return AttrSpaceportExhibitNumberKey.Int(val)
}

// --- Enum values ---


// Enum values for error.type.
const (
    // A fallback error value to be used when the instrumentation doesn't define a
// custom value.
    AttrErrorTypeOther = "_OTHER"
)

// Enum values for http.connection.state.
const (
    // active state.
    AttrHttpConnectionStateActive = "active"
    // idle state.
    AttrHttpConnectionStateIdle = "idle"
)

// Enum values for http.flavor.
const (
    // HTTP/1.0
    AttrHttpFlavorHttp10 = "1.0"
    // HTTP/1.1
    AttrHttpFlavorHttp11 = "1.1"
    // HTTP/2
    AttrHttpFlavorHttp20 = "2.0"
    // HTTP/3
    AttrHttpFlavorHttp30 = "3.0"
    // SPDY protocol.
    AttrHttpFlavorSpdy = "SPDY"
    // QUIC protocol.
    AttrHttpFlavorQuic = "QUIC"
)

// Enum values for http.request.method.
const (
    // CONNECT method.
    AttrHttpRequestMethodConnect = "CONNECT"
    // DELETE method.
    AttrHttpRequestMethodDelete = "DELETE"
    // GET method.
    AttrHttpRequestMethodGet = "GET"
    // HEAD method.
    AttrHttpRequestMethodHead = "HEAD"
    // OPTIONS method.
    AttrHttpRequestMethodOptions = "OPTIONS"
    // PATCH method.
    AttrHttpRequestMethodPatch = "PATCH"
    // POST method.
    AttrHttpRequestMethodPost = "POST"
    // PUT method.
    AttrHttpRequestMethodPut = "PUT"
    // TRACE method.
    AttrHttpRequestMethodTrace = "TRACE"
    // QUERY method.
    AttrHttpRequestMethodQuery = "QUERY"
    // Any HTTP method that the instrumentation has no prior knowledge of.
    AttrHttpRequestMethodOther = "_OTHER"
)

// Enum values for network.connection.state.
const (
    
    AttrNetworkConnectionStateClosed = "closed"
    
    AttrNetworkConnectionStateCloseWait = "close_wait"
    
    AttrNetworkConnectionStateClosing = "closing"
    
    AttrNetworkConnectionStateEstablished = "established"
    
    AttrNetworkConnectionStateFinWait1 = "fin_wait_1"
    
    AttrNetworkConnectionStateFinWait2 = "fin_wait_2"
    
    AttrNetworkConnectionStateLastAck = "last_ack"
    
    AttrNetworkConnectionStateListen = "listen"
    
    AttrNetworkConnectionStateSynReceived = "syn_received"
    
    AttrNetworkConnectionStateSynSent = "syn_sent"
    
    AttrNetworkConnectionStateTimeWait = "time_wait"
)

// Enum values for network.connection.subtype.
const (
    // GPRS
    AttrNetworkConnectionSubtypeGprs = "gprs"
    // EDGE
    AttrNetworkConnectionSubtypeEdge = "edge"
    // UMTS
    AttrNetworkConnectionSubtypeUmts = "umts"
    // CDMA
    AttrNetworkConnectionSubtypeCdma = "cdma"
    // EVDO Rel. 0
    AttrNetworkConnectionSubtypeEvdo0 = "evdo_0"
    // EVDO Rev. A
    AttrNetworkConnectionSubtypeEvdoA = "evdo_a"
    // CDMA2000 1XRTT
    AttrNetworkConnectionSubtypeCdma20001xrtt = "cdma2000_1xrtt"
    // HSDPA
    AttrNetworkConnectionSubtypeHsdpa = "hsdpa"
    // HSUPA
    AttrNetworkConnectionSubtypeHsupa = "hsupa"
    // HSPA
    AttrNetworkConnectionSubtypeHspa = "hspa"
    // IDEN
    AttrNetworkConnectionSubtypeIden = "iden"
    // EVDO Rev. B
    AttrNetworkConnectionSubtypeEvdoB = "evdo_b"
    // LTE
    AttrNetworkConnectionSubtypeLte = "lte"
    // EHRPD
    AttrNetworkConnectionSubtypeEhrpd = "ehrpd"
    // HSPAP
    AttrNetworkConnectionSubtypeHspap = "hspap"
    // GSM
    AttrNetworkConnectionSubtypeGsm = "gsm"
    // TD-SCDMA
    AttrNetworkConnectionSubtypeTdScdma = "td_scdma"
    // IWLAN
    AttrNetworkConnectionSubtypeIwlan = "iwlan"
    // 5G NR (New Radio)
    AttrNetworkConnectionSubtypeNr = "nr"
    // 5G NRNSA (New Radio Non-Standalone)
    AttrNetworkConnectionSubtypeNrnsa = "nrnsa"
    // LTE CA
    AttrNetworkConnectionSubtypeLteCa = "lte_ca"
)

// Enum values for network.connection.type.
const (
    
    AttrNetworkConnectionTypeWifi = "wifi"
    
    AttrNetworkConnectionTypeWired = "wired"
    
    AttrNetworkConnectionTypeCell = "cell"
    
    AttrNetworkConnectionTypeUnavailable = "unavailable"
    
    AttrNetworkConnectionTypeUnknown = "unknown"
)

// Enum values for network.io.direction.
const (
    
    AttrNetworkIoDirectionTransmit = "transmit"
    
    AttrNetworkIoDirectionReceive = "receive"
)

// Enum values for network.transport.
const (
    // TCP
    AttrNetworkTransportTcp = "tcp"
    // UDP
    AttrNetworkTransportUdp = "udp"
    // Named or anonymous pipe.
    AttrNetworkTransportPipe = "pipe"
    // Unix domain socket
    AttrNetworkTransportUnix = "unix"
    // QUIC
    AttrNetworkTransportQuic = "quic"
)

// Enum values for network.type.
const (
    // IPv4
    AttrNetworkTypeIpv4 = "ipv4"
    // IPv6
    AttrNetworkTypeIpv6 = "ipv6"
)

// Enum values for spaceport.booking.status.
const (
    // Booking was successfully confirmed.
    AttrSpaceportBookingStatusConfirmed = "confirmed"
    // Booking failed.
    AttrSpaceportBookingStatusFailed = "failed"
)

// Enum values for spaceport.pricing.display_currency.
const (
    // Universal Nano Credits
    AttrSpaceportPricingDisplayCurrencyUnc = "UNC"
    // Republic Credits
    AttrSpaceportPricingDisplayCurrencyRep = "REP"
    // Latinum
    AttrSpaceportPricingDisplayCurrencyLat = "LAT"
    // Quatloos
    AttrSpaceportPricingDisplayCurrencyQua = "QUA"
    // Ningi
    AttrSpaceportPricingDisplayCurrencyNin = "NIN"
    // Breen Dilithium
    AttrSpaceportPricingDisplayCurrencyBzd = "BZD"
    // Space Coin
    AttrSpaceportPricingDisplayCurrencyCoin = "COIN"
    // Token
    AttrSpaceportPricingDisplayCurrencyTkn = "TKN"
)

// Enum values for spaceport.seat.class.
const (
    // Economy class with cryosleep pod.
    AttrSpaceportSeatClassEconomyCryosleep = "economy-cryosleep"
    // Business class with warp-lounge access.
    AttrSpaceportSeatClassBusinessWarp = "business-warp"
    // First class nebula suite.
    AttrSpaceportSeatClassFirstClassNebula = "first-class-nebula"
)