package semconv

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/metric.go.j2.


// This is used as a helper for all optional attributes.
type attr struct {
	kv attribute.KeyValue
}
func (a attr) attr() attribute.KeyValue {
    return a.kv
}


type OptionalAttr interface {
    attr() attribute.KeyValue
}







// An instrument for recording `spaceport.booking.active`
type SpaceportBookingActive struct {
    inst metric.Float64UpDownCounter
}

// Construct a new instrument for measuring `spaceport.booking.active`
func NewSpaceportBookingActive(m metric.Meter) (SpaceportBookingActive, error) {
    i, err := m.Float64UpDownCounter(
        "spaceport.booking.active",
        metric.WithDescription("Number of confirmed bookings currently in the system."),
        metric.WithUnit("{booking}"),
    )
    if err != nil {
        return SpaceportBookingActive{}, err
    }
    return SpaceportBookingActive{i}, nil
}




func spaceportBookingActiveAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}




// Adds an increment to the existing count.
func (m SpaceportBookingActive) Add(
    ctx context.Context,
    inc float64,




    optAttrs ...OptionalAttr,


) {
    
    m.inst.Add(ctx, inc, metric.WithAttributes(
    
        
        append(spaceportBookingActiveAttrToAttrs(optAttrs),
        
        
        
        
        
        )...,
        
    ))
}








// An instrument for recording `spaceport.booking.count`
type SpaceportBookingCount struct {
    inst metric.Float64Counter
}

// Construct a new instrument for measuring `spaceport.booking.count`
func NewSpaceportBookingCount(m metric.Meter) (SpaceportBookingCount, error) {
    i, err := m.Float64Counter(
        "spaceport.booking.count",
        metric.WithDescription("Number of booking attempts processed by the API."),
        metric.WithUnit("{booking}"),
    )
    if err != nil {
        return SpaceportBookingCount{}, err
    }
    return SpaceportBookingCount{i}, nil
}




func spaceportBookingCountAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}




// Adds an increment to the existing count.
func (m SpaceportBookingCount) Add(
    ctx context.Context,
    inc float64,



    // Status of the booking.
    spaceportBookingStatus string,


    optAttrs ...OptionalAttr,


) {
    
    m.inst.Add(ctx, inc, metric.WithAttributes(
    
        
        append(spaceportBookingCountAttrToAttrs(optAttrs),
        
        
        
        attribute.String("spaceport.booking.status", spaceportBookingStatus),
        
        
        
        )...,
        
    ))
}








// An instrument for recording `spaceport.departure.active`
type SpaceportDepartureActive struct {
    inst metric.Float64UpDownCounter
}

// Construct a new instrument for measuring `spaceport.departure.active`
func NewSpaceportDepartureActive(m metric.Meter) (SpaceportDepartureActive, error) {
    i, err := m.Float64UpDownCounter(
        "spaceport.departure.active",
        metric.WithDescription("Number of departures currently available for booking."),
        metric.WithUnit("{departure}"),
    )
    if err != nil {
        return SpaceportDepartureActive{}, err
    }
    return SpaceportDepartureActive{i}, nil
}




func spaceportDepartureActiveAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}




// Adds an increment to the existing count.
func (m SpaceportDepartureActive) Add(
    ctx context.Context,
    inc float64,




    optAttrs ...OptionalAttr,


) {
    
    m.inst.Add(ctx, inc, metric.WithAttributes(
    
        
        append(spaceportDepartureActiveAttrToAttrs(optAttrs),
        
        
        
        
        
        )...,
        
    ))
}








// An instrument for recording `spaceport.pricing.request.duration`
type SpaceportPricingRequestDuration struct {
    inst metric.Float64Histogram
}

// Construct a new instrument for measuring `spaceport.pricing.request.duration`
func NewSpaceportPricingRequestDuration(m metric.Meter) (SpaceportPricingRequestDuration, error) {
    i, err := m.Float64Histogram(
        "spaceport.pricing.request.duration",
        metric.WithDescription("Duration of price calculation requests from the API to the pricing service."),
        metric.WithUnit("ms"),
    )
    if err != nil {
        return SpaceportPricingRequestDuration{}, err
    }
    return SpaceportPricingRequestDuration{i}, nil
}




func spaceportPricingRequestDurationAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}




// Records a value in the histogram.
func (m SpaceportPricingRequestDuration) Record(
    ctx context.Context,
    value float64,



    // The seat class selected for the booking.
    spaceportSeatClass string,


    optAttrs ...OptionalAttr,


) {
    
    m.inst.Record(ctx, value, metric.WithAttributes(
    
        
        append(spaceportPricingRequestDurationAttrToAttrs(optAttrs),
        
        
        
        attribute.String("spaceport.seat.class", spaceportSeatClass),
        
        
        
        )...,
        
    ))
}






func SpaceportDepartureDestination(spaceportDepartureDestination string) OptionalAttr {
	return attr{attribute.String("spaceport.departure.destination", spaceportDepartureDestination)}
}

func SpaceportPricingDisplayCurrency(spaceportPricingDisplayCurrency string) OptionalAttr {
	return attr{attribute.String("spaceport.pricing.display_currency", spaceportPricingDisplayCurrency)}
}

func SpaceportPricingPromoApplied(spaceportPricingPromoApplied bool) OptionalAttr {
	return attr{attribute.Bool("spaceport.pricing.promo_applied", spaceportPricingPromoApplied)}
}

func SpaceportSeatClass(spaceportSeatClass string) OptionalAttr {
	return attr{attribute.String("spaceport.seat.class", spaceportSeatClass)}
}

func SpaceportChaosFailureMode(spaceportChaosFailureMode string) OptionalAttr {
	return attr{attribute.String("spaceport.chaos.failure_mode", spaceportChaosFailureMode)}
}
