package semconv

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/metric"
)

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/metric.go.j2.

// This is used as a helper for all optional attributes.
type attr struct {
	kv attribute.KeyValue
}
func (a attr) attr() attribute.KeyValue {
    return a.kv
}

type OptionalAttr interface {
    attr() attribute.KeyValue
}

// An instrument for recording `http.server.active_requests`
type HttpServerActiveRequests struct {
    inst metric.Float64UpDownCounter
}

// Construct a new instrument for measuring `http.server.active_requests`
func NewHttpServerActiveRequests(m metric.Meter) (HttpServerActiveRequests, error) {
    i, err := m.Float64UpDownCounter(
        "http.server.active_requests",
        metric.WithDescription("Number of active HTTP server requests."),
        metric.WithUnit("{request}"),
    )
    if err != nil {
        return HttpServerActiveRequests{}, err
    }
    return HttpServerActiveRequests{i}, nil
}

func httpServerActiveRequestsAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Adds an increment to the existing count.
func (m HttpServerActiveRequests) Add(
    ctx context.Context,
    inc float64,
    // HTTP request method.
    httpRequestMethod string,
    // The [URI scheme] component identifying the used protocol.
//
// [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
    urlScheme string,
    optAttrs ...OptionalAttr,
) {
    m.inst.Add(ctx, inc, metric.WithAttributes(
        append(httpServerActiveRequestsAttrToAttrs(optAttrs),
        attribute.String("http.request.method", httpRequestMethod),
        attribute.String("url.scheme", urlScheme),
        )...,
    ))
}

// An instrument for recording `http.server.request.duration`
type HttpServerRequestDuration struct {
    inst metric.Float64Histogram
}

// Construct a new instrument for measuring `http.server.request.duration`
func NewHttpServerRequestDuration(m metric.Meter) (HttpServerRequestDuration, error) {
    i, err := m.Float64Histogram(
        "http.server.request.duration",
        metric.WithDescription("Duration of HTTP server requests."),
        metric.WithUnit("s"),
    )
    if err != nil {
        return HttpServerRequestDuration{}, err
    }
    return HttpServerRequestDuration{i}, nil
}

func httpServerRequestDurationAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Records a value in the histogram.
func (m HttpServerRequestDuration) Record(
    ctx context.Context,
    value float64,
    // HTTP request method.
    httpRequestMethod string,
    // The [URI scheme] component identifying the used protocol.
//
// [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
    urlScheme string,
    optAttrs ...OptionalAttr,
) {
    m.inst.Record(ctx, value, metric.WithAttributes(
        append(httpServerRequestDurationAttrToAttrs(optAttrs),
        attribute.String("http.request.method", httpRequestMethod),
        attribute.String("url.scheme", urlScheme),
        )...,
    ))
}

// An instrument for recording `spaceport.booking.active`
type SpaceportBookingActive struct {
    inst metric.Float64UpDownCounter
}

// Construct a new instrument for measuring `spaceport.booking.active`
func NewSpaceportBookingActive(m metric.Meter) (SpaceportBookingActive, error) {
    i, err := m.Float64UpDownCounter(
        "spaceport.booking.active",
        metric.WithDescription("Number of confirmed bookings currently in the system."),
        metric.WithUnit("{booking}"),
    )
    if err != nil {
        return SpaceportBookingActive{}, err
    }
    return SpaceportBookingActive{i}, nil
}

func spaceportBookingActiveAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Adds an increment to the existing count.
func (m SpaceportBookingActive) Add(
    ctx context.Context,
    inc float64,
    optAttrs ...OptionalAttr,
) {
    m.inst.Add(ctx, inc, metric.WithAttributes(
        spaceportBookingActiveAttrToAttrs(optAttrs)...,
    ))
}

// An instrument for recording `spaceport.booking.count`
type SpaceportBookingCount struct {
    inst metric.Float64Counter
}

// Construct a new instrument for measuring `spaceport.booking.count`
func NewSpaceportBookingCount(m metric.Meter) (SpaceportBookingCount, error) {
    i, err := m.Float64Counter(
        "spaceport.booking.count",
        metric.WithDescription("Number of booking attempts processed by the API."),
        metric.WithUnit("{booking}"),
    )
    if err != nil {
        return SpaceportBookingCount{}, err
    }
    return SpaceportBookingCount{i}, nil
}

func spaceportBookingCountAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Adds an increment to the existing count.
func (m SpaceportBookingCount) Add(
    ctx context.Context,
    inc float64,
    // Status of the booking.
    spaceportBookingStatus string,
    optAttrs ...OptionalAttr,
) {
    m.inst.Add(ctx, inc, metric.WithAttributes(
        append(spaceportBookingCountAttrToAttrs(optAttrs),
        attribute.String("spaceport.booking.status", spaceportBookingStatus),
        )...,
    ))
}

// An instrument for recording `spaceport.departure.active`
type SpaceportDepartureActive struct {
    inst metric.Float64UpDownCounter
}

// Construct a new instrument for measuring `spaceport.departure.active`
func NewSpaceportDepartureActive(m metric.Meter) (SpaceportDepartureActive, error) {
    i, err := m.Float64UpDownCounter(
        "spaceport.departure.active",
        metric.WithDescription("Number of departures currently available for booking."),
        metric.WithUnit("{departure}"),
    )
    if err != nil {
        return SpaceportDepartureActive{}, err
    }
    return SpaceportDepartureActive{i}, nil
}

func spaceportDepartureActiveAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Adds an increment to the existing count.
func (m SpaceportDepartureActive) Add(
    ctx context.Context,
    inc float64,
    optAttrs ...OptionalAttr,
) {
    m.inst.Add(ctx, inc, metric.WithAttributes(
        spaceportDepartureActiveAttrToAttrs(optAttrs)...,
    ))
}

// An instrument for recording `spaceport.pricing.request.duration`
type SpaceportPricingRequestDuration struct {
    inst metric.Float64Histogram
}

// Construct a new instrument for measuring `spaceport.pricing.request.duration`
func NewSpaceportPricingRequestDuration(m metric.Meter) (SpaceportPricingRequestDuration, error) {
    i, err := m.Float64Histogram(
        "spaceport.pricing.request.duration",
        metric.WithDescription("Duration of price calculation requests from the API to the pricing service."),
        metric.WithUnit("ms"),
    )
    if err != nil {
        return SpaceportPricingRequestDuration{}, err
    }
    return SpaceportPricingRequestDuration{i}, nil
}

func spaceportPricingRequestDurationAttrToAttrs(in []OptionalAttr) []attribute.KeyValue {
	out := make([]attribute.KeyValue, len(in))
	for i, a := range in {
		out[i] = a.attr()
	}
	return out
}
// Records a value in the histogram.
func (m SpaceportPricingRequestDuration) Record(
    ctx context.Context,
    value float64,
    // The seat class selected for the booking.
    spaceportSeatClass string,
    optAttrs ...OptionalAttr,
) {
    m.inst.Record(ctx, value, metric.WithAttributes(
        append(spaceportPricingRequestDurationAttrToAttrs(optAttrs),
        attribute.String("spaceport.seat.class", spaceportSeatClass),
        )...,
    ))
}


func ErrorType(errorType string) OptionalAttr {
	return attr{attribute.String("error.type", errorType)}
}

func HttpResponseStatusCode(httpResponseStatusCode int) OptionalAttr {
	return attr{attribute.Int("http.response.status_code", httpResponseStatusCode)}
}

func HttpRoute(httpRoute string) OptionalAttr {
	return attr{attribute.String("http.route", httpRoute)}
}

func NetworkProtocolName(networkProtocolName string) OptionalAttr {
	return attr{attribute.String("network.protocol.name", networkProtocolName)}
}

func NetworkProtocolVersion(networkProtocolVersion string) OptionalAttr {
	return attr{attribute.String("network.protocol.version", networkProtocolVersion)}
}

func SpaceportDepartureDestination(spaceportDepartureDestination string) OptionalAttr {
	return attr{attribute.String("spaceport.departure.destination", spaceportDepartureDestination)}
}

func SpaceportPricingDisplayCurrency(spaceportPricingDisplayCurrency string) OptionalAttr {
	return attr{attribute.String("spaceport.pricing.display_currency", spaceportPricingDisplayCurrency)}
}

func SpaceportPricingPromoApplied(spaceportPricingPromoApplied bool) OptionalAttr {
	return attr{attribute.Bool("spaceport.pricing.promo_applied", spaceportPricingPromoApplied)}
}

func SpaceportSeatClass(spaceportSeatClass string) OptionalAttr {
	return attr{attribute.String("spaceport.seat.class", spaceportSeatClass)}
}

func ServerAddress(serverAddress string) OptionalAttr {
	return attr{attribute.String("server.address", serverAddress)}
}

func ServerPort(serverPort int) OptionalAttr {
	return attr{attribute.Int("server.port", serverPort)}
}

func SpaceportChaosFailureMode(spaceportChaosFailureMode string) OptionalAttr {
	return attr{attribute.String("spaceport.chaos.failure_mode", spaceportChaosFailureMode)}
}

func UserAgentSyntheticType(userAgentSyntheticType string) OptionalAttr {
	return attr{attribute.String("user_agent.synthetic.type", userAgentSyntheticType)}
}