package semconv

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/span.go.j2.


// SpanSpaceportBookingCreateServerName is the span name for: Handles an incoming booking creation request in the API.
const SpanSpaceportBookingCreateServerName = "spaceport.booking.create.server"

// Handles an incoming booking creation request in the API.
func StartSpaceportBookingCreateServer(ctx context.Context, tracer trace.Tracer,
    spaceportBookingId string,
    spaceportBookingStatus string,
    spaceportDepartureId string,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
        trace.WithAttributes(
            attribute.String("spaceport.booking.id", spaceportBookingId),
            attribute.String("spaceport.booking.status", spaceportBookingStatus),
            attribute.String("spaceport.departure.id", spaceportDepartureId),
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportBookingCreateServerName, opts...)
}

// SpanSpaceportBookingListServerName is the span name for: Handles a request to list all bookings from the API.
const SpanSpaceportBookingListServerName = "spaceport.booking.list.server"

// Handles a request to list all bookings from the API.
func StartSpaceportBookingListServer(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportBookingListServerName, opts...)
}

// SpanSpaceportDepartureListServerName is the span name for: Handles a request to list available departures from the API.
const SpanSpaceportDepartureListServerName = "spaceport.departure.list.server"

// Handles a request to list available departures from the API.
func StartSpaceportDepartureListServer(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportDepartureListServerName, opts...)
}

// SpanSpaceportPricingCalculateClientName is the span name for: Outbound call from the API to the pricing service to calculate a fare.
const SpanSpaceportPricingCalculateClientName = "spaceport.pricing.calculate.client"

// Outbound call from the API to the pricing service to calculate a fare.
func StartSpaceportPricingCalculateClient(ctx context.Context, tracer trace.Tracer,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindClient),
        trace.WithAttributes(
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportPricingCalculateClientName, opts...)
}