package semconv

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/span.go.j2.


// SpanSpaceportApiCallRecommendationServiceClientName is the span name for: Outbound call from the API to the recommendation service.
const SpanSpaceportApiCallRecommendationServiceClientName = "spaceport.api.call_recommendation_service.client"

// Outbound call from the API to the recommendation service.
func StartSpaceportApiCallRecommendationServiceClient(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindClient),
    )
    return tracer.Start(ctx, SpanSpaceportApiCallRecommendationServiceClientName, opts...)
}

// SpanSpaceportAppLoadCurrenciesInternalName is the span name for: Loading available currencies from the API on app startup.
const SpanSpaceportAppLoadCurrenciesInternalName = "spaceport.app.load_currencies.internal"

// Loading available currencies from the API on app startup.
func StartSpaceportAppLoadCurrenciesInternal(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
    )
    return tracer.Start(ctx, SpanSpaceportAppLoadCurrenciesInternalName, opts...)
}

// SpanSpaceportBookingCreateServerName is the span name for: Handles an incoming booking creation request in the API.
const SpanSpaceportBookingCreateServerName = "spaceport.booking.create.server"

// Handles an incoming booking creation request in the API.
func StartSpaceportBookingCreateServer(ctx context.Context, tracer trace.Tracer,
    spaceportBookingId string,
    spaceportBookingStatus string,
    spaceportDepartureId string,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
        trace.WithAttributes(
            attribute.String("spaceport.booking.id", spaceportBookingId),
            attribute.String("spaceport.booking.status", spaceportBookingStatus),
            attribute.String("spaceport.departure.id", spaceportDepartureId),
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportBookingCreateServerName, opts...)
}

// SpanSpaceportBookingListServerName is the span name for: Handles a request to list all bookings from the API.
const SpanSpaceportBookingListServerName = "spaceport.booking.list.server"

// Handles a request to list all bookings from the API.
func StartSpaceportBookingListServer(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportBookingListServerName, opts...)
}

// SpanSpaceportDepartureListServerName is the span name for: Handles a request to list available departures from the API.
const SpanSpaceportDepartureListServerName = "spaceport.departure.list.server"

// Handles a request to list available departures from the API.
func StartSpaceportDepartureListServer(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportDepartureListServerName, opts...)
}

// SpanSpaceportExhibitViewInternalName is the span name for: Tracks a single exhibit visible in the viewport, linked to the page span.
const SpanSpaceportExhibitViewInternalName = "spaceport.exhibit.view.internal"

// Tracks a single exhibit visible in the viewport, linked to the page span.
func StartSpaceportExhibitViewInternal(ctx context.Context, tracer trace.Tracer,
    spaceportExhibitId string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
        trace.WithAttributes(
            attribute.String("spaceport.exhibit.id", spaceportExhibitId),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportExhibitViewInternalName, opts...)
}

// SpanSpaceportPricingCalculateClientName is the span name for: Outbound call from the API to the pricing service to calculate a fare.
const SpanSpaceportPricingCalculateClientName = "spaceport.pricing.calculate.client"

// Outbound call from the API to the pricing service to calculate a fare.
func StartSpaceportPricingCalculateClient(ctx context.Context, tracer trace.Tracer,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindClient),
        trace.WithAttributes(
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportPricingCalculateClientName, opts...)
}

// SpanSpaceportPricingCalculateServerName is the span name for: Server-side price calculation in the pricing service.
const SpanSpaceportPricingCalculateServerName = "spaceport.pricing.calculate.server"

// Server-side price calculation in the pricing service.
func StartSpaceportPricingCalculateServer(ctx context.Context, tracer trace.Tracer,
    spaceportDepartureId string,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
        trace.WithAttributes(
            attribute.String("spaceport.departure.id", spaceportDepartureId),
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportPricingCalculateServerName, opts...)
}

// SpanSpaceportPricingRecommendServerName is the span name for: Server-side recommendation generation in the pricing service.
const SpanSpaceportPricingRecommendServerName = "spaceport.pricing.recommend.server"

// Server-side recommendation generation in the pricing service.
func StartSpaceportPricingRecommendServer(ctx context.Context, tracer trace.Tracer,
    spaceportDepartureId string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
        trace.WithAttributes(
            attribute.String("spaceport.departure.id", spaceportDepartureId),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportPricingRecommendServerName, opts...)
}

// SpanSpaceportUserBrowseDeparturesInternalName is the span name for: Tracks a user browsing the departure list page.
const SpanSpaceportUserBrowseDeparturesInternalName = "spaceport.user.browse_departures.internal"

// Tracks a user browsing the departure list page.
func StartSpaceportUserBrowseDeparturesInternal(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
    )
    return tracer.Start(ctx, SpanSpaceportUserBrowseDeparturesInternalName, opts...)
}

// SpanSpaceportUserChangeCurrencyInternalName is the span name for: User switches the display currency in the frontend.
const SpanSpaceportUserChangeCurrencyInternalName = "spaceport.user.change_currency.internal"

// User switches the display currency in the frontend.
func StartSpaceportUserChangeCurrencyInternal(ctx context.Context, tracer trace.Tracer,
    spaceportPricingBaseCurrency string,
    spaceportPricingDisplayCurrency string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
        trace.WithAttributes(
            attribute.String("spaceport.pricing.base_currency", spaceportPricingBaseCurrency),
            attribute.String("spaceport.pricing.display_currency", spaceportPricingDisplayCurrency),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportUserChangeCurrencyInternalName, opts...)
}

// SpanSpaceportUserPlaceBookingInternalName is the span name for: Tracks a user submitting a booking from the frontend.
const SpanSpaceportUserPlaceBookingInternalName = "spaceport.user.place_booking.internal"

// Tracks a user submitting a booking from the frontend.
func StartSpaceportUserPlaceBookingInternal(ctx context.Context, tracer trace.Tracer,
    spaceportDepartureId string,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
        trace.WithAttributes(
            attribute.String("spaceport.departure.id", spaceportDepartureId),
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportUserPlaceBookingInternalName, opts...)
}

// SpanSpaceportUserViewDepartureInternalName is the span name for: Tracks a user viewing a specific departure detail page.
const SpanSpaceportUserViewDepartureInternalName = "spaceport.user.view_departure.internal"

// Tracks a user viewing a specific departure detail page.
func StartSpaceportUserViewDepartureInternal(ctx context.Context, tracer trace.Tracer,
    spaceportDepartureId string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
        trace.WithAttributes(
            attribute.String("spaceport.departure.id", spaceportDepartureId),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportUserViewDepartureInternalName, opts...)
}

// SpanSpaceportUserViewInformationDeskInternalName is the span name for: Tracks a user session on the Information Desk page, from mount to unmount. Child exhibit_viewed events are added as the user scrolls.

const SpanSpaceportUserViewInformationDeskInternalName = "spaceport.user.view_information_desk.internal"

// Tracks a user session on the Information Desk page, from mount to unmount.
// Child exhibit_viewed events are added as the user scrolls.
func StartSpaceportUserViewInformationDeskInternal(ctx context.Context, tracer trace.Tracer,
    spaceportExhibitCount int,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindInternal),
        trace.WithAttributes(
            attribute.Int("spaceport.exhibit.count", spaceportExhibitCount),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportUserViewInformationDeskInternalName, opts...)
}