package semconv

import (
	"context"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
)

// DO NOT MODIFY: This code is autogenerated.
// See templates/registry/go/span.go.j2.


// SpanSpaceportBookingCreateName is the span name for: Handles an incoming booking creation request in the API.
const SpanSpaceportBookingCreateName = "spaceport.booking.create"

// Handles an incoming booking creation request in the API.
func StartSpaceportBookingCreate(ctx context.Context, tracer trace.Tracer,
    spaceportBookingId string,
    spaceportBookingStatus string,
    spaceportDepartureId string,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
        trace.WithAttributes(
            attribute.String("spaceport.booking.id", spaceportBookingId),
            attribute.String("spaceport.booking.status", spaceportBookingStatus),
            attribute.String("spaceport.departure.id", spaceportDepartureId),
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportBookingCreateName, opts...)
}

// SpanSpaceportBookingListName is the span name for: Handles a request to list all bookings from the API.
const SpanSpaceportBookingListName = "spaceport.booking.list"

// Handles a request to list all bookings from the API.
func StartSpaceportBookingList(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportBookingListName, opts...)
}

// SpanSpaceportDepartureListName is the span name for: Handles a request to list available departures from the API.
const SpanSpaceportDepartureListName = "spaceport.departure.list"

// Handles a request to list available departures from the API.
func StartSpaceportDepartureList(ctx context.Context, tracer trace.Tracer,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindServer),
    )
    return tracer.Start(ctx, SpanSpaceportDepartureListName, opts...)
}

// SpanSpaceportPricingCalculateName is the span name for: Outbound call from the API to the pricing service to calculate a fare.
const SpanSpaceportPricingCalculateName = "spaceport.pricing.calculate"

// Outbound call from the API to the pricing service to calculate a fare.
func StartSpaceportPricingCalculate(ctx context.Context, tracer trace.Tracer,
    spaceportSeatClass string,
    opts ...trace.SpanStartOption,
) (context.Context, trace.Span) {
    opts = append(opts,
        trace.WithSpanKind(trace.SpanKindClient),
        trace.WithAttributes(
            attribute.String("spaceport.seat.class", spaceportSeatClass),
        ),
    )
    return tracer.Start(ctx, SpanSpaceportPricingCalculateName, opts...)
}