/**
 * Semantic convention attribute constants.
 *
 * DO NOT MODIFY: This code is autogenerated.
 * See templates/registry/typescript/attribute.ts.j2.
 */

// --- Attribute keys ---

// Deprecated, use `client.address` instead.
export const HTTP_CLIENT_IP = "http.client_ip";
// State of the HTTP connection in the HTTP connection pool.
export const HTTP_CONNECTION_STATE = "http.connection.state";
// Deprecated, use `network.protocol.name` and `network.protocol.version`
// instead.
export const HTTP_FLAVOR = "http.flavor";
// Deprecated, use one of `server.address`, `client.address` or
// `http.request.header.host` instead, depending on the usage.
export const HTTP_HOST = "http.host";
// Deprecated, use `http.request.method` instead.
export const HTTP_METHOD = "http.method";
// The size of the request payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
export const HTTP_REQUEST_BODY_SIZE = "http.request.body.size";
// HTTP request headers, `<key>` being the normalized HTTP Header name
// (lowercase), the value being the header values.
export const HTTP_REQUEST_HEADER = "http.request.header";
// HTTP request method.
export const HTTP_REQUEST_METHOD = "http.request.method";
// Original HTTP method sent by the client in the request line.
export const HTTP_REQUEST_METHOD_ORIGINAL = "http.request.method_original";
// The ordinal number of request resending attempt (for any reason, including
// redirects).
export const HTTP_REQUEST_RESEND_COUNT = "http.request.resend_count";
// The total size of the request in bytes. This should be the total number of
// bytes sent over the wire, including the request line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and request body if any.
export const HTTP_REQUEST_SIZE = "http.request.size";
// Deprecated, use `http.request.header.content-length` instead.
export const HTTP_REQUEST_CONTENT_LENGTH = "http.request_content_length";
// Deprecated, use `http.request.body.size` instead.
export const HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED = "http.request_content_length_uncompressed";
// The size of the response payload body in bytes. This is the number of bytes
// transferred excluding headers and is often, but not always, present as the
// [Content-Length] header. For requests using transport encoding, this should be
// the compressed size.
//
// [Content-Length]: https://www.rfc-editor.org/rfc/rfc9110.html#field.content-length
export const HTTP_RESPONSE_BODY_SIZE = "http.response.body.size";
// HTTP response headers, `<key>` being the normalized HTTP Header name
// (lowercase), the value being the header values.
export const HTTP_RESPONSE_HEADER = "http.response.header";
// The total size of the response in bytes. This should be the total number of
// bytes sent over the wire, including the status line (HTTP/1.1), framing
// (HTTP/2 and HTTP/3), headers, and response body and trailers if any.
export const HTTP_RESPONSE_SIZE = "http.response.size";
// [HTTP response status code].
//
// [HTTP response status code]: https://tools.ietf.org/html/rfc7231#section-6
export const HTTP_RESPONSE_STATUS_CODE = "http.response.status_code";
// Deprecated, use `http.response.header.content-length` instead.
export const HTTP_RESPONSE_CONTENT_LENGTH = "http.response_content_length";
// Deprecated, use `http.response.body.size` instead.
export const HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED = "http.response_content_length_uncompressed";
// The matched route template for the request. This MUST be low-cardinality and
// include all static path segments, with dynamic path segments represented with
// placeholders.
export const HTTP_ROUTE = "http.route";
// Deprecated, use `url.scheme` instead.
export const HTTP_SCHEME = "http.scheme";
// Deprecated, use `server.address` instead.
export const HTTP_SERVER_NAME = "http.server_name";
// Deprecated, use `http.response.status_code` instead.
export const HTTP_STATUS_CODE = "http.status_code";
// Deprecated, use `url.path` and `url.query` instead.
export const HTTP_TARGET = "http.target";
// Deprecated, use `url.full` instead.
export const HTTP_URL = "http.url";
// Deprecated, use `user_agent.original` instead.
export const HTTP_USER_AGENT = "http.user_agent";
// Unique identifier for the booking.
export const SPACEPORT_BOOKING_ID = "spaceport.booking.id";
// Status of the booking.
export const SPACEPORT_BOOKING_STATUS = "spaceport.booking.status";
// The type of failure injected by the chaos module.
export const SPACEPORT_CHAOS_FAILURE_MODE = "spaceport.chaos.failure_mode";
// Artificial latency injected by the chaos module in milliseconds.
export const SPACEPORT_CHAOS_LATENCY_MS = "spaceport.chaos.latency_ms";
// Scheduled departure time in ISO 8601 format.
export const SPACEPORT_DEPARTURE_DEPARTURE_TIME = "spaceport.departure.departure_time";
// Destination of the departure (e.g. planet, station, or sector name).
export const SPACEPORT_DEPARTURE_DESTINATION = "spaceport.departure.destination";
// Unique identifier for the departure.
export const SPACEPORT_DEPARTURE_ID = "spaceport.departure.id";
// URL-safe slug identifying the exhibit section.
export const SPACEPORT_EXHIBIT_ID = "spaceport.exhibit.id";
// Human-readable title of the exhibit.
export const SPACEPORT_EXHIBIT_TITLE = "spaceport.exhibit.title";
// The base currency used for pricing. Always "UNC".
export const SPACEPORT_PRICING_BASE_CURRENCY = "spaceport.pricing.base_currency";
// The currency in which the price is displayed to the user.
export const SPACEPORT_PRICING_DISPLAY_CURRENCY = "spaceport.pricing.display_currency";
// Error message returned by the pricing service on failure.
export const SPACEPORT_PRICING_ERROR = "spaceport.pricing.error";
// Whether a promotional discount was applied to the booking.
export const SPACEPORT_PRICING_PROMO_APPLIED = "spaceport.pricing.promo_applied";
// Total price of the booking in Universal Nano Credits (UNC).
export const SPACEPORT_PRICING_TOTAL = "spaceport.pricing.total";
// Error message returned by the recommendations service on failure.
export const SPACEPORT_RECOMMENDATIONS_ERROR = "spaceport.recommendations.error";
// The seat class selected for the booking.
export const SPACEPORT_SEAT_CLASS = "spaceport.seat.class";
// Domain extracted from the `url.full`, such as "opentelemetry.io".
export const URL_DOMAIN = "url.domain";
// The file extension extracted from the `url.full`, excluding the leading dot.
export const URL_EXTENSION = "url.extension";
// The [URI fragment] component
//
// [URI fragment]: https://www.rfc-editor.org/rfc/rfc3986#section-3.5
export const URL_FRAGMENT = "url.fragment";
// Absolute URL describing a network resource according to [RFC3986]
//
// [RFC3986]: https://www.rfc-editor.org/rfc/rfc3986
export const URL_FULL = "url.full";
// Unmodified original URL as seen in the event source.
export const URL_ORIGINAL = "url.original";
// The [URI path] component
//
// [URI path]: https://www.rfc-editor.org/rfc/rfc3986#section-3.3
export const URL_PATH = "url.path";
// Port extracted from the `url.full`
export const URL_PORT = "url.port";
// The [URI query] component
//
// [URI query]: https://www.rfc-editor.org/rfc/rfc3986#section-3.4
export const URL_QUERY = "url.query";
// The highest registered url domain, stripped of the subdomain.
export const URL_REGISTERED_DOMAIN = "url.registered_domain";
// The [URI scheme] component identifying the used protocol.
//
// [URI scheme]: https://www.rfc-editor.org/rfc/rfc3986#section-3.1
export const URL_SCHEME = "url.scheme";
// The subdomain portion of a fully qualified domain name includes all of the
// names except the host name under the registered_domain. In a partially
// qualified domain, or if the qualification level of the full name cannot be
// determined, subdomain contains all of the names below the registered domain.
export const URL_SUBDOMAIN = "url.subdomain";
// The low-cardinality template of an [absolute path reference].
//
// [absolute path reference]: https://www.rfc-editor.org/rfc/rfc3986#section-4.2
export const URL_TEMPLATE = "url.template";
// The effective top level domain (eTLD), also known as the domain suffix, is the
// last part of the domain name. For example, the top level domain for
// example.com is `com`.
export const URL_TOP_LEVEL_DOMAIN = "url.top_level_domain";
// Total number of exhibits available in the presentation.
export const SPACEPORT_EXHIBIT_COUNT = "spaceport.exhibit.count";
// Display order number of the exhibit (1-based).
export const SPACEPORT_EXHIBIT_NUMBER = "spaceport.exhibit.number";

// --- Enum values ---


// Enum values for http.connection.state.
export const HTTP_CONNECTION_STATE_ACTIVE = "active";
export const HTTP_CONNECTION_STATE_IDLE = "idle";

// Enum values for http.flavor.
export const HTTP_FLAVOR_HTTP_1_0 = "1.0";
export const HTTP_FLAVOR_HTTP_1_1 = "1.1";
export const HTTP_FLAVOR_HTTP_2_0 = "2.0";
export const HTTP_FLAVOR_HTTP_3_0 = "3.0";
export const HTTP_FLAVOR_SPDY = "SPDY";
export const HTTP_FLAVOR_QUIC = "QUIC";

// Enum values for http.request.method.
export const HTTP_REQUEST_METHOD_CONNECT = "CONNECT";
export const HTTP_REQUEST_METHOD_DELETE = "DELETE";
export const HTTP_REQUEST_METHOD_GET = "GET";
export const HTTP_REQUEST_METHOD_HEAD = "HEAD";
export const HTTP_REQUEST_METHOD_OPTIONS = "OPTIONS";
export const HTTP_REQUEST_METHOD_PATCH = "PATCH";
export const HTTP_REQUEST_METHOD_POST = "POST";
export const HTTP_REQUEST_METHOD_PUT = "PUT";
export const HTTP_REQUEST_METHOD_TRACE = "TRACE";
export const HTTP_REQUEST_METHOD_QUERY = "QUERY";
export const HTTP_REQUEST_METHOD_OTHER = "_OTHER";

// Enum values for spaceport.booking.status.
export const SPACEPORT_BOOKING_STATUS_CONFIRMED = "confirmed";
export const SPACEPORT_BOOKING_STATUS_FAILED = "failed";

// Enum values for spaceport.pricing.display_currency.
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_UNC = "UNC";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_REP = "REP";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_LAT = "LAT";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_QUA = "QUA";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_NIN = "NIN";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_BZD = "BZD";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_COIN = "COIN";
export const SPACEPORT_PRICING_DISPLAY_CURRENCY_TKN = "TKN";

// Enum values for spaceport.seat.class.
export const SPACEPORT_SEAT_CLASS_ECONOMY_CRYOSLEEP = "economy-cryosleep";
export const SPACEPORT_SEAT_CLASS_BUSINESS_WARP = "business-warp";
export const SPACEPORT_SEAT_CLASS_FIRST_CLASS_NEBULA = "first-class-nebula";