/**
 * Semantic convention metric instruments.
 *
 * DO NOT MODIFY: This code is autogenerated.
 * See templates/registry/typescript/metric.ts.j2.
 */

import type { Meter, Counter, Histogram, UpDownCounter } from "@opentelemetry/api";

/**
 * Number of active HTTP server requests.
 *
 * Instrument: updowncounter | Unit: {request}
 */
export class HttpServerActiveRequests {
  static readonly name = "http.server.active_requests";
  static readonly unit = "{request}";
  static readonly description = "Number of active HTTP server requests.";

  private readonly inst: UpDownCounter;

  constructor(meter: Meter) {
    this.inst = meter.createUpDownCounter(
      HttpServerActiveRequests.name,
      {
        description: HttpServerActiveRequests.description,
        unit: HttpServerActiveRequests.unit,
      },
    );
  }

  add(
    value: number,
    http_request_method: string,
    url_scheme: string,
    options?: {
      server_address?: string;
      server_port?: number;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "http.request.method": http_request_method,
      "url.scheme": url_scheme,
    };
    if (options?.server_address !== undefined) {
      attrs["server.address"] = options.server_address;
    }
    if (options?.server_port !== undefined) {
      attrs["server.port"] = options.server_port;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Duration of HTTP server requests.
 *
 * Instrument: histogram | Unit: s
 */
export class HttpServerRequestDuration {
  static readonly name = "http.server.request.duration";
  static readonly unit = "s";
  static readonly description = "Duration of HTTP server requests.";

  private readonly inst: Histogram;

  constructor(meter: Meter) {
    this.inst = meter.createHistogram(
      HttpServerRequestDuration.name,
      {
        description: HttpServerRequestDuration.description,
        unit: HttpServerRequestDuration.unit,
      },
    );
  }

  record(
    value: number,
    http_request_method: string,
    url_scheme: string,
    options?: {
      error_type?: string;
      http_response_status_code?: number;
      http_route?: string;
      network_protocol_name?: string;
      network_protocol_version?: string;
      server_address?: string;
      server_port?: number;
      user_agent_synthetic_type?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "http.request.method": http_request_method,
      "url.scheme": url_scheme,
    };
    if (options?.error_type !== undefined) {
      attrs["error.type"] = options.error_type;
    }
    if (options?.http_response_status_code !== undefined) {
      attrs["http.response.status_code"] = options.http_response_status_code;
    }
    if (options?.http_route !== undefined) {
      attrs["http.route"] = options.http_route;
    }
    if (options?.network_protocol_name !== undefined) {
      attrs["network.protocol.name"] = options.network_protocol_name;
    }
    if (options?.network_protocol_version !== undefined) {
      attrs["network.protocol.version"] = options.network_protocol_version;
    }
    if (options?.server_address !== undefined) {
      attrs["server.address"] = options.server_address;
    }
    if (options?.server_port !== undefined) {
      attrs["server.port"] = options.server_port;
    }
    if (options?.user_agent_synthetic_type !== undefined) {
      attrs["user_agent.synthetic.type"] = options.user_agent_synthetic_type;
    }
    this.inst.record(value, attrs);
  }
}

/**
 * Number of confirmed bookings currently in the system.
 *
 * Instrument: updowncounter | Unit: {booking}
 */
export class SpaceportBookingActive {
  static readonly name = "spaceport.booking.active";
  static readonly unit = "{booking}";
  static readonly description = "Number of confirmed bookings currently in the system.";

  private readonly inst: UpDownCounter;

  constructor(meter: Meter) {
    this.inst = meter.createUpDownCounter(
      SpaceportBookingActive.name,
      {
        description: SpaceportBookingActive.description,
        unit: SpaceportBookingActive.unit,
      },
    );
  }

  add(
    value: number,
    options?: {
      spaceport_seat_class?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
    };
    if (options?.spaceport_seat_class !== undefined) {
      attrs["spaceport.seat.class"] = options.spaceport_seat_class;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Number of booking attempts processed by the API.
 *
 * Instrument: counter | Unit: {booking}
 */
export class SpaceportBookingCount {
  static readonly name = "spaceport.booking.count";
  static readonly unit = "{booking}";
  static readonly description = "Number of booking attempts processed by the API.";

  private readonly inst: Counter;

  constructor(meter: Meter) {
    this.inst = meter.createCounter(
      SpaceportBookingCount.name,
      {
        description: SpaceportBookingCount.description,
        unit: SpaceportBookingCount.unit,
      },
    );
  }

  add(
    value: number,
    spaceport_booking_status: string,
    options?: {
      spaceport_departure_destination?: string;
      spaceport_seat_class?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "spaceport.booking.status": spaceport_booking_status,
    };
    if (options?.spaceport_departure_destination !== undefined) {
      attrs["spaceport.departure.destination"] = options.spaceport_departure_destination;
    }
    if (options?.spaceport_seat_class !== undefined) {
      attrs["spaceport.seat.class"] = options.spaceport_seat_class;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Number of departures currently available for booking.
 *
 * Instrument: updowncounter | Unit: {departure}
 */
export class SpaceportDepartureActive {
  static readonly name = "spaceport.departure.active";
  static readonly unit = "{departure}";
  static readonly description = "Number of departures currently available for booking.";

  private readonly inst: UpDownCounter;

  constructor(meter: Meter) {
    this.inst = meter.createUpDownCounter(
      SpaceportDepartureActive.name,
      {
        description: SpaceportDepartureActive.description,
        unit: SpaceportDepartureActive.unit,
      },
    );
  }

  add(
    value: number,
    options?: {
      spaceport_departure_destination?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
    };
    if (options?.spaceport_departure_destination !== undefined) {
      attrs["spaceport.departure.destination"] = options.spaceport_departure_destination;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Booking attempts made from the frontend.
 *
 * Instrument: counter | Unit: {booking}
 */
export class SpaceportFrontendBookings {
  static readonly name = "spaceport.frontend.bookings";
  static readonly unit = "{booking}";
  static readonly description = "Booking attempts made from the frontend.";

  private readonly inst: Counter;

  constructor(meter: Meter) {
    this.inst = meter.createCounter(
      SpaceportFrontendBookings.name,
      {
        description: SpaceportFrontendBookings.description,
        unit: SpaceportFrontendBookings.unit,
      },
    );
  }

  add(
    value: number,
    outcome: string,
    options?: {
      spaceport_seat_class?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "outcome": outcome,
    };
    if (options?.spaceport_seat_class !== undefined) {
      attrs["spaceport.seat.class"] = options.spaceport_seat_class;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Time an exhibit remained visible in the viewport.
 *
 * Instrument: histogram | Unit: s
 */
export class SpaceportFrontendExhibitDwellTime {
  static readonly name = "spaceport.frontend.exhibit_dwell_time";
  static readonly unit = "s";
  static readonly description = "Time an exhibit remained visible in the viewport.";

  private readonly inst: Histogram;

  constructor(meter: Meter) {
    this.inst = meter.createHistogram(
      SpaceportFrontendExhibitDwellTime.name,
      {
        description: SpaceportFrontendExhibitDwellTime.description,
        unit: SpaceportFrontendExhibitDwellTime.unit,
      },
    );
  }

  record(
    value: number,
    spaceport_exhibit_id: string,
    options?: {
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "spaceport.exhibit.id": spaceport_exhibit_id,
    };
    this.inst.record(value, attrs);
  }
}

/**
 * Number of times an exhibit section scrolled into the viewport.
 *
 * Instrument: counter | Unit: {view}
 */
export class SpaceportFrontendExhibitViews {
  static readonly name = "spaceport.frontend.exhibit_views";
  static readonly unit = "{view}";
  static readonly description = "Number of times an exhibit section scrolled into the viewport.";

  private readonly inst: Counter;

  constructor(meter: Meter) {
    this.inst = meter.createCounter(
      SpaceportFrontendExhibitViews.name,
      {
        description: SpaceportFrontendExhibitViews.description,
        unit: SpaceportFrontendExhibitViews.unit,
      },
    );
  }

  add(
    value: number,
    spaceport_exhibit_id: string,
    options?: {
      spaceport_exhibit_title?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "spaceport.exhibit.id": spaceport_exhibit_id,
    };
    if (options?.spaceport_exhibit_title !== undefined) {
      attrs["spaceport.exhibit.title"] = options.spaceport_exhibit_title;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Page views counted by page name.
 *
 * Instrument: counter | Unit: {view}
 */
export class SpaceportFrontendPageViews {
  static readonly name = "spaceport.frontend.page_views";
  static readonly unit = "{view}";
  static readonly description = "Page views counted by page name.";

  private readonly inst: Counter;

  constructor(meter: Meter) {
    this.inst = meter.createCounter(
      SpaceportFrontendPageViews.name,
      {
        description: SpaceportFrontendPageViews.description,
        unit: SpaceportFrontendPageViews.unit,
      },
    );
  }

  add(
    value: number,
    page_name: string,
    options?: {
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "page.name": page_name,
    };
    this.inst.add(value, attrs);
  }
}

/**
 * Number of pricing service call failures from the API.
 *
 * Instrument: counter | Unit: {failure}
 */
export class SpaceportPricingFailuresCount {
  static readonly name = "spaceport.pricing.failures.count";
  static readonly unit = "{failure}";
  static readonly description = "Number of pricing service call failures from the API.";

  private readonly inst: Counter;

  constructor(meter: Meter) {
    this.inst = meter.createCounter(
      SpaceportPricingFailuresCount.name,
      {
        description: SpaceportPricingFailuresCount.description,
        unit: SpaceportPricingFailuresCount.unit,
      },
    );
  }

  add(
    value: number,
    options?: {
      spaceport_seat_class?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
    };
    if (options?.spaceport_seat_class !== undefined) {
      attrs["spaceport.seat.class"] = options.spaceport_seat_class;
    }
    this.inst.add(value, attrs);
  }
}

/**
 * Duration of price calculation requests from the API to the pricing service.
 *
 * Instrument: histogram | Unit: ms
 */
export class SpaceportPricingRequestDuration {
  static readonly name = "spaceport.pricing.request.duration";
  static readonly unit = "ms";
  static readonly description = "Duration of price calculation requests from the API to the pricing service.";

  private readonly inst: Histogram;

  constructor(meter: Meter) {
    this.inst = meter.createHistogram(
      SpaceportPricingRequestDuration.name,
      {
        description: SpaceportPricingRequestDuration.description,
        unit: SpaceportPricingRequestDuration.unit,
      },
    );
  }

  record(
    value: number,
    spaceport_seat_class: string,
    options?: {
      spaceport_pricing_display_currency?: string;
      spaceport_pricing_promo_applied?: boolean;
      spaceport_chaos_failure_mode?: string;
    },
  ): void {
    const attrs: Record<string, string | number | boolean> = {
      "spaceport.seat.class": spaceport_seat_class,
    };
    if (options?.spaceport_pricing_display_currency !== undefined) {
      attrs["spaceport.pricing.display_currency"] = options.spaceport_pricing_display_currency;
    }
    if (options?.spaceport_pricing_promo_applied !== undefined) {
      attrs["spaceport.pricing.promo_applied"] = options.spaceport_pricing_promo_applied;
    }
    if (options?.spaceport_chaos_failure_mode !== undefined) {
      attrs["spaceport.chaos.failure_mode"] = options.spaceport_chaos_failure_mode;
    }
    this.inst.record(value, attrs);
  }
}