/**
 * Semantic convention span helpers.
 *
 * DO NOT MODIFY: This code is autogenerated.
 * See templates/registry/typescript/span.ts.j2.
 */

import type { Tracer, Span } from "@opentelemetry/api";
import { SpanKind } from "@opentelemetry/api";

/** Span name for: Outbound call from the API to the recommendation service. */
export const SPAN_SPACEPORT_API_CALL_RECOMMENDATION_SERVICE_CLIENT_NAME = "spaceport.api.call_recommendation_service.client";

// Outbound call from the API to the recommendation service.
export function startSpaceportApiCallRecommendationServiceClient(
  tracer: Tracer,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_API_CALL_RECOMMENDATION_SERVICE_CLIENT_NAME, {
    kind: SpanKind.CLIENT,
    attributes: {
    },
  });
}

/** Span name for: Loading available currencies from the API on app startup. */
export const SPAN_SPACEPORT_APP_LOAD_CURRENCIES_INTERNAL_NAME = "spaceport.app.load_currencies.internal";

// Loading available currencies from the API on app startup.
export function startSpaceportAppLoadCurrenciesInternal(
  tracer: Tracer,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_APP_LOAD_CURRENCIES_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
    },
  });
}

/** Span name for: Handles an incoming booking creation request in the API. */
export const SPAN_SPACEPORT_BOOKING_CREATE_SERVER_NAME = "spaceport.booking.create.server";

// Handles an incoming booking creation request in the API.
export function startSpaceportBookingCreateServer(
  tracer: Tracer,
  spaceport_booking_id: string,
  spaceport_booking_status: string,
  spaceport_departure_id: string,
  spaceport_seat_class: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_BOOKING_CREATE_SERVER_NAME, {
    kind: SpanKind.SERVER,
    attributes: {
      "spaceport.booking.id": spaceport_booking_id,
      "spaceport.booking.status": spaceport_booking_status,
      "spaceport.departure.id": spaceport_departure_id,
      "spaceport.seat.class": spaceport_seat_class,
    },
  });
}

/** Span name for: Handles a request to list all bookings from the API. */
export const SPAN_SPACEPORT_BOOKING_LIST_SERVER_NAME = "spaceport.booking.list.server";

// Handles a request to list all bookings from the API.
export function startSpaceportBookingListServer(
  tracer: Tracer,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_BOOKING_LIST_SERVER_NAME, {
    kind: SpanKind.SERVER,
    attributes: {
    },
  });
}

/** Span name for: Handles a request to list available departures from the API. */
export const SPAN_SPACEPORT_DEPARTURE_LIST_SERVER_NAME = "spaceport.departure.list.server";

// Handles a request to list available departures from the API.
export function startSpaceportDepartureListServer(
  tracer: Tracer,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_DEPARTURE_LIST_SERVER_NAME, {
    kind: SpanKind.SERVER,
    attributes: {
    },
  });
}

/** Span name for: Tracks a single exhibit visible in the viewport, linked to the page span. */
export const SPAN_SPACEPORT_EXHIBIT_VIEW_INTERNAL_NAME = "spaceport.exhibit.view.internal";

// Tracks a single exhibit visible in the viewport, linked to the page span.
export function startSpaceportExhibitViewInternal(
  tracer: Tracer,
  spaceport_exhibit_id: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_EXHIBIT_VIEW_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
      "spaceport.exhibit.id": spaceport_exhibit_id,
    },
  });
}

/** Span name for: Outbound call from the API to the pricing service to calculate a fare. */
export const SPAN_SPACEPORT_PRICING_CALCULATE_CLIENT_NAME = "spaceport.pricing.calculate.client";

// Outbound call from the API to the pricing service to calculate a fare.
export function startSpaceportPricingCalculateClient(
  tracer: Tracer,
  spaceport_seat_class: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_PRICING_CALCULATE_CLIENT_NAME, {
    kind: SpanKind.CLIENT,
    attributes: {
      "spaceport.seat.class": spaceport_seat_class,
    },
  });
}

/** Span name for: Server-side price calculation in the pricing service. */
export const SPAN_SPACEPORT_PRICING_CALCULATE_SERVER_NAME = "spaceport.pricing.calculate.server";

// Server-side price calculation in the pricing service.
export function startSpaceportPricingCalculateServer(
  tracer: Tracer,
  spaceport_departure_id: string,
  spaceport_seat_class: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_PRICING_CALCULATE_SERVER_NAME, {
    kind: SpanKind.SERVER,
    attributes: {
      "spaceport.departure.id": spaceport_departure_id,
      "spaceport.seat.class": spaceport_seat_class,
    },
  });
}

/** Span name for: Server-side recommendation generation in the pricing service. */
export const SPAN_SPACEPORT_PRICING_RECOMMEND_SERVER_NAME = "spaceport.pricing.recommend.server";

// Server-side recommendation generation in the pricing service.
export function startSpaceportPricingRecommendServer(
  tracer: Tracer,
  spaceport_departure_id: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_PRICING_RECOMMEND_SERVER_NAME, {
    kind: SpanKind.SERVER,
    attributes: {
      "spaceport.departure.id": spaceport_departure_id,
    },
  });
}

/** Span name for: Tracks a user browsing the departure list page. */
export const SPAN_SPACEPORT_USER_BROWSE_DEPARTURES_INTERNAL_NAME = "spaceport.user.browse_departures.internal";

// Tracks a user browsing the departure list page.
export function startSpaceportUserBrowseDeparturesInternal(
  tracer: Tracer,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_USER_BROWSE_DEPARTURES_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
    },
  });
}

/** Span name for: User switches the display currency in the frontend. */
export const SPAN_SPACEPORT_USER_CHANGE_CURRENCY_INTERNAL_NAME = "spaceport.user.change_currency.internal";

// User switches the display currency in the frontend.
export function startSpaceportUserChangeCurrencyInternal(
  tracer: Tracer,
  spaceport_pricing_base_currency: string,
  spaceport_pricing_display_currency: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_USER_CHANGE_CURRENCY_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
      "spaceport.pricing.base_currency": spaceport_pricing_base_currency,
      "spaceport.pricing.display_currency": spaceport_pricing_display_currency,
    },
  });
}

/** Span name for: Tracks a user submitting a booking from the frontend. */
export const SPAN_SPACEPORT_USER_PLACE_BOOKING_INTERNAL_NAME = "spaceport.user.place_booking.internal";

// Tracks a user submitting a booking from the frontend.
export function startSpaceportUserPlaceBookingInternal(
  tracer: Tracer,
  spaceport_departure_id: string,
  spaceport_seat_class: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_USER_PLACE_BOOKING_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
      "spaceport.departure.id": spaceport_departure_id,
      "spaceport.seat.class": spaceport_seat_class,
    },
  });
}

/** Span name for: Tracks a user viewing a specific departure detail page. */
export const SPAN_SPACEPORT_USER_VIEW_DEPARTURE_INTERNAL_NAME = "spaceport.user.view_departure.internal";

// Tracks a user viewing a specific departure detail page.
export function startSpaceportUserViewDepartureInternal(
  tracer: Tracer,
  spaceport_departure_id: string,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_USER_VIEW_DEPARTURE_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
      "spaceport.departure.id": spaceport_departure_id,
    },
  });
}

/** Span name for: Tracks a user session on the Information Desk page, from mount to unmount. Child exhibit_viewed events are added as the user scrolls.  */
export const SPAN_SPACEPORT_USER_VIEW_INFORMATION_DESK_INTERNAL_NAME = "spaceport.user.view_information_desk.internal";

// Tracks a user session on the Information Desk page, from mount to unmount.
// Child exhibit_viewed events are added as the user scrolls.
export function startSpaceportUserViewInformationDeskInternal(
  tracer: Tracer,
  spaceport_exhibit_count: number,
): Span {
  return tracer.startSpan(SPAN_SPACEPORT_USER_VIEW_INFORMATION_DESK_INTERNAL_NAME, {
    kind: SpanKind.INTERNAL,
    attributes: {
      "spaceport.exhibit.count": spaceport_exhibit_count,
    },
  });
}