enabled: false

otlpEndpoint: "http://otel-collector:4318"

ingress:
  enabled: true
  host: "spaceport.k8s.test"

grafana:
  provisioning:
    enabled: true
    folder: "/etc/grafana/provisioning/dashboards/spaceport"

frontend:
  image:
    repository: ghcr.io/fiddeb/spaceport-frontend
    # tag defaults to Chart.appVersion when empty
    tag: ""
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

api:
  image:
    repository: ghcr.io/fiddeb/spaceport-api
    # tag defaults to Chart.appVersion when empty
    tag: ""
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

pricingService:
  image:
    repository: ghcr.io/fiddeb/spaceport-pricing-service
    # tag defaults to Chart.appVersion when empty
    tag: ""
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
